// Adds a "Haxe" language tab to every function on the fmod.com API
// reference. The site renders each function as an h2[api="function"], a
// language selector with C, C++, C#, and JS tabs, and one highlight block
// per language. This script appends a fifth tab and block, filled from
// HAXEFMOD_BINDINGS (bindings-data.js, generated by ci/haxe-bindings.py).
//
// The site's own selector only knows its four language classes, so the
// Haxe tab manages its own selection state and hides itself when another
// tab is picked.
(function () {
    "use strict";

    var LANG = "language-haxe";
    var STORAGE_KEY = "FMOD.Documents.selected-language";
    // The site validates the stored language against the ones a page
    // offers and rewrites the key when it finds ours, so the Haxe choice
    // keeps its own flag as well.
    var OWN_KEY = "haxefmod.selected";
    var NATIVE_LANGS = ["language-c", "language-cpp", "language-c-cpp", "language-csharp", "language-javascript"];
    var GUIDES = "https://tanz0rz.github.io/haxe-fmod/";
    var DATA = typeof HAXEFMOD_BINDINGS !== "undefined" ? HAXEFMOD_BINDINGS : null;

    if (!DATA) return;

    function el(tag, className, text) {
        var node = document.createElement(tag);
        if (className) node.className = className;
        if (text != null) node.textContent = text;
        return node;
    }

    function shortType(type) {
        return type.split(".").pop();
    }

    // Static methods are called on the type, instance methods on a value
    // of it, which the receiver name shows without a comment.
    function receiver(m) {
        var name = shortType(m.type);
        return m.static ? name : name.charAt(0).toLowerCase() + name.slice(1);
    }

    function renderBlock(entry) {
        var block = el("div", "highlight " + LANG + " haxefmod-block");
        block.style.display = "none";
        var pre = el("pre");
        var note = el("div", "haxefmod-note");

        if (!entry || entry.haxe.length === 0) {
            pre.textContent = "// Not exposed by haxefmod";
            var limits = el("a", null, "Limitations");
            limits.href = GUIDES + "limitations/";
            limits.target = "_blank";
            note.appendChild(document.createTextNode("This function has no haxefmod binding. See "));
            note.appendChild(limits);
            note.appendChild(document.createTextNode(" for what is left out and why."));
        } else {
            var direct = entry.haxe.filter(function (m) { return m.direct; });
            var also = entry.haxe.filter(function (m) { return !m.direct; });
            var shown = direct.length ? direct : also;
            var rest = direct.length ? also : [];
            var lines = [];
            var seenTypes = {};
            shown.forEach(function (m) {
                if (!seenTypes[m.type]) {
                    seenTypes[m.type] = true;
                    lines.push("import " + m.type + ";");
                }
            });
            lines.push("");
            shown.forEach(function (m) {
                lines.push(receiver(m) + "." + m.signature);
            });
            pre.textContent = lines.join("\n");

            var doc = "";
            for (var i = 0; i < shown.length && !doc; i++) doc = shown[i].doc;
            if (doc) note.appendChild(el("p", null, doc));
            if (rest.length) {
                var names = rest.map(function (m) { return shortType(m.type) + "." + m.name; });
                note.appendChild(el("p", null, "Also reaches this function: " + names.join(", ")));
            }
            if (entry.html5) {
                note.appendChild(el("p", "haxefmod-warn", "HTML5: FMOD's web build does not support this call, haxefmod reports FMOD_ERR_UNSUPPORTED there."));
            }
        }

        var footer = el("p", "haxefmod-footer");
        footer.appendChild(document.createTextNode("haxefmod " + DATA.haxefmod + " for FMOD " + DATA.fmod + ". "));
        var link = el("a", null, "Guides and API reference");
        link.href = GUIDES;
        link.target = "_blank";
        footer.appendChild(link);
        note.appendChild(footer);

        block.appendChild(pre);
        block.appendChild(note);
        return block;
    }

    function lastHighlight(selector) {
        var last = null;
        var node = selector.nextElementSibling;
        while (node) {
            var isHighlight = node.tagName === "DIV" && node.classList.contains("highlight");
            var isSpacer = node.tagName === "P" && node.textContent.trim() === "";
            if (isHighlight) last = node;
            else if (!isSpacer) break;
            node = node.nextElementSibling;
        }
        return last;
    }

    function inject(heading) {
        if (heading.dataset.haxefmod) return;
        var selector = null;
        var node = heading.nextElementSibling;
        for (var i = 0; node && i < 4; i++) {
            if (node.classList && node.classList.contains("language-selector")) { selector = node; break; }
            node = node.nextElementSibling;
        }
        if (!selector) return;
        var anchor = lastHighlight(selector);
        if (!anchor) return;
        heading.dataset.haxefmod = "1";

        var tab = el("div", "language-tab haxefmod-tab", "Haxe");
        tab.setAttribute("data-language", LANG);
        selector.appendChild(tab);

        var block = renderBlock(DATA.entries[heading.id]);
        anchor.parentNode.insertBefore(block, anchor.nextSibling);
    }

    function injectAll() {
        var root = document.querySelector("div.manual-content.api");
        if (!root) return false;
        var headings = root.querySelectorAll('h2[api="function"]');
        for (var i = 0; i < headings.length; i++) inject(headings[i]);
        return headings.length > 0;
    }

    function setDisplay(selectorList, display) {
        var nodes = document.querySelectorAll(selectorList);
        for (var i = 0; i < nodes.length; i++) nodes[i].style.display = display;
    }

    function apply(selected) {
        var haxeOn = selected === LANG;
        setDisplay("." + LANG, haxeOn ? "block" : "none");
        var tabs = document.querySelectorAll(".language-tab");
        for (var i = 0; i < tabs.length; i++) {
            var lang = tabs[i].getAttribute("data-language");
            if (lang === LANG) tabs[i].classList.toggle("selected", haxeOn);
            else if (haxeOn) tabs[i].classList.remove("selected");
        }
        if (haxeOn) {
            setDisplay(NATIVE_LANGS.map(function (l) { return "." + l; }).join(", "), "none");
        }
    }

    function haxeChosen() {
        try { return window.localStorage.getItem(OWN_KEY) === "1"; } catch (e) { return false; }
    }

    function choose(haxe) {
        try {
            if (haxe) {
                window.localStorage.setItem(OWN_KEY, "1");
                window.localStorage.setItem(STORAGE_KEY, LANG);
            } else {
                window.localStorage.removeItem(OWN_KEY);
            }
        } catch (e) { /* storage unavailable, selection lasts for the page only */ }
    }

    document.addEventListener("click", function (event) {
        var tab = event.target.closest ? event.target.closest(".language-tab") : null;
        if (!tab) return;
        var lang = tab.getAttribute("data-language");
        if (lang === LANG) {
            choose(true);
            apply(LANG);
        } else {
            choose(false);
            apply(lang);
        }
    });

    var pending = false;
    function schedule() {
        if (pending) return;
        pending = true;
        window.requestAnimationFrame(function () {
            pending = false;
            if (injectAll() && haxeChosen()) {
                choose(true);
                apply(LANG);
                // The site's selector initializes after render and may
                // run later than this pass. Reapply once it has settled.
                window.setTimeout(function () { apply(LANG); }, 50);
            }
        });
    }

    new MutationObserver(schedule).observe(document.documentElement, { childList: true, subtree: true });
    schedule();
})();
