// Adds a "Haxe" language tab to every function on the fmod.com API
// reference. The site renders each function as an h2[api="function"], a
// language selector with C, C++, C#, and JS tabs, and one highlight block
// per language. This script appends a fifth tab and block, filled from
// HAXEFMOD_BINDINGS (bindings-data.js, generated by ci/haxe-bindings.py), and does the same for
// every other code block from HAXEFMOD_EXAMPLES (examples-data.js,
// generated by ci/haxe-catalog.py), keyed by extension/keys.js.
//
// The site's own selector only knows its four language classes, so the
// Haxe tab manages its own selection state and hides itself when another
// tab is picked.
(function () {
    "use strict";

    var LANG = "language-haxe";
    var STORAGE_KEY = "FMOD.Documents.selected-language";
    // The site validates the stored language against the ones a page
    // offers and rewrites the key when it finds ours, so the Haxe choice
    // keeps its own flag as well.
    var OWN_KEY = "haxefmod.selected";
    var NATIVE_LANGS = ["language-c", "language-cpp", "language-c-cpp", "language-csharp", "language-javascript"];
    var GUIDES = "https://tanz0rz.github.io/haxe-fmod/";
    var DATA = typeof HAXEFMOD_BINDINGS !== "undefined" ? HAXEFMOD_BINDINGS : null;
    var EXAMPLES = typeof HAXEFMOD_EXAMPLES !== "undefined" ? HAXEFMOD_EXAMPLES : {};

    if (!DATA) return;

    function pageName() {
        var file = window.location.pathname.split("/").pop() || "";
        return file.replace(/\.html$/, "");
    }

    var WARN_COLOR = "#a40000";

    function el(tag, className, text) {
        var node = document.createElement(tag);
        if (className) node.className = className;
        if (text != null) node.textContent = text;
        // The site styles text inside highlight blocks with rules that win
        // over a content script's stylesheet, so the warning colour goes
        // on the element itself
        if (className && className.indexOf("haxefmod-warn-title") >= 0) node.style.color = WARN_COLOR;
        return node;
    }

    function shortType(type) {
        return type.split(".").pop();
    }

    // Splits an argument list on the commas outside <>, {}, and ().
    function splitArgs(text) {
        var out = [];
        var depth = 0;
        var current = "";
        for (var i = 0; i < text.length; i++) {
            var c = text.charAt(i);
            if (c === "<" || c === "{" || c === "(") depth++;
            if (c === ">" || c === "}" || c === ")") depth--;
            if (c === "," && depth === 0) { out.push(current.trim()); current = ""; continue; }
            current += c;
        }
        if (current.trim()) out.push(current.trim());
        return out;
    }

    // The site prints a zero-argument signature on one line and every
    // other signature with one argument per line, ending with a
    // semicolon. The Haxe tab follows that shape.
    function formatSignature(prefix, signature) {
        var open = signature.indexOf("(");
        var close = signature.lastIndexOf(")");
        var name = signature.slice(0, open);
        var args = splitArgs(signature.slice(open + 1, close));
        var ret = signature.slice(close + 1);
        if (args.length === 0) return prefix + "." + name + "()" + ret + ";";
        return prefix + "." + name + "(\n  " + args.join(",\n  ") + "\n)" + ret + ";";
    }

    // Static methods are called on the type, instance methods on a value
    // of it, which the receiver name shows without a comment.
    // The site prints every language as a type-qualified declaration
    // (Sound::set3DConeSettings, Studio.EventInstance.start), so the Haxe
    // tab qualifies with the Haxe type the same way, static or not.
    // The other tabs qualify the function with its package (C# prints
    // Studio.EventInstance.start), so the Haxe tab prints the full type
    // path, which is the valid Haxe form of the same reference
    function receiver(m) {
        return m.type;
    }

    function renderBlock(entry) {
        var block = el("div", "highlight " + LANG + " haxefmod-block");
        block.style.display = "none";
        var pre = el("pre");
        var note = el("div", "haxefmod-note");

        var notes = entry && entry.notes ? entry.notes : [];
        if (!entry || entry.haxe.length === 0) {
            // A function haxefmod does not reach shows one comment line:
            // the verdict and its reason from functions.md ("Cannot be
            // bound. ...", "No Haxe declaration, another call plays this
            // role. ...", or the library's own step). No note at all is a
            // gap in the notes file, so say so on the page.
            if (!notes.length) {
                pre.textContent = "// Not exposed by haxefmod";
                note.appendChild(el("p", "haxefmod-warn", "haxefmod has no binding for this function and no note explaining why. Please report it."));
            } else {
                pre.textContent = "// " + notes[0];
            }
        } else {
            var direct = entry.haxe.filter(function (m) { return m.direct; });
            var also = entry.haxe.filter(function (m) { return !m.direct; });
            var shown = direct.length ? direct : also;
            var rest = direct.length ? also : [];
            var lines = [];
            shown.forEach(function (m, i) {
                if (i > 0) lines.push("");
                lines.push(formatSignature(receiver(m), m.signature));
            });
            pre.textContent = lines.join("\n");


            // The page already describes the function above the tabs, so
            // the note carries only what is specific to the Haxe side.
            if (rest.length) {
                var names = rest.map(function (m) { return shortType(m.type) + "." + m.name; });
                note.appendChild(el("p", null, "Also reaches this function: " + names.join(", ")));
            }
            if (entry.gated) {
                var warn = el("div", "haxefmod-warn");
                warn.appendChild(el("p", "haxefmod-warn-title", "HTML5 BUILD TARGET UNSUPPORTED"));
                var list = el("ul", "haxefmod-warn-list");
                list.appendChild(el("li", "haxefmod-warn-item", "FMOD's web build does not support this feature, so the call does not compile in a js build."));
                list.appendChild(el("li", "haxefmod-warn-item", "The build flag haxefmod_html5_allow_unsupported compiles it anyway, and it then returns FMOD_ERR_UNSUPPORTED at runtime."));
                warn.appendChild(list);
                note.appendChild(warn);
            } else if (entry.html5) {
                var limited = el("p", "haxefmod-warn");
                limited.appendChild(el("span", "haxefmod-warn-title", "Warning - "));
                limited.appendChild(document.createTextNode("HTML5: FMOD's web build does not support this call, haxefmod reports FMOD_ERR_UNSUPPORTED there."));
                note.appendChild(limited);
            }
            notes.forEach(function (text) { note.appendChild(el("p", null, text)); });
        }

        note.appendChild(footer());

        block.appendChild(pre);
        block.appendChild(note);
        return block;
    }

    function footer() {
        var line = el("p", "haxefmod-footer");
        line.appendChild(document.createTextNode("haxefmod " + DATA.haxefmod + " for FMOD " + DATA.fmod + ". "));
        var link = el("a", null, "Guides and API reference");
        link.href = GUIDES;
        link.target = "_blank";
        line.appendChild(link);
        return line;
    }

    // A guide example: hand-written Haxe for the C++ sample above it, or
    // a note when haxefmod has no equivalent.
    // A guide example shows code only, like the other tabs. A note that
    // explains a difference rides along as comment lines above the code,
    // and an example with no Haxe equivalent is a comment on its own.
    function renderExample(example) {
        var block = el("div", "highlight " + LANG + " haxefmod-block");
        block.style.display = "none";
        var lines = [];
        example.notes.forEach(function (text) { lines.push("// " + text); });
        if (example.code != null) {
            if (lines.length) lines.push("");
            lines.push(example.code);
        }
        var pre = el("pre");
        pre.textContent = lines.join("\n");
        block.appendChild(pre);
        var note = el("div", "haxefmod-note");
        if (example.type) note.appendChild(el("p", "haxefmod-type", example.type));
        note.appendChild(footer());
        block.appendChild(note);
        return block;
    }

    function lastHighlight(selector) {
        var last = null;
        var node = selector.nextElementSibling;
        while (node) {
            var isHighlight = node.tagName === "DIV" && node.classList.contains("highlight");
            var isSpacer = node.tagName === "P" && node.textContent.trim() === "";
            if (isHighlight) last = node;
            else if (!isSpacer) break;
            node = node.nextElementSibling;
        }
        return last;
    }

    function addTab(selector, block) {
        var anchor = lastHighlight(selector);
        if (!anchor) return false;
        var tab = el("div", "language-tab haxefmod-tab", "Haxe");
        tab.setAttribute("data-language", LANG);
        selector.appendChild(tab);
        anchor.parentNode.insertBefore(block, anchor.nextSibling);
        return true;
    }

    // Lone examples get a selector of their own so the Haxe tab has a
    // place to live. The original language keeps the site's tab class,
    // so the site's selector logic treats it like any other block.
    function selectorForLone(highlight) {
        var lang = null;
        for (var i = 0; i < highlight.classList.length; i++) {
            if (highlight.classList[i].indexOf("language-") === 0) lang = highlight.classList[i];
        }
        var labels = { "language-c": "C", "language-cpp": "C++", "language-csharp": "C#", "language-javascript": "JS" };
        var selector = el("div", "language-selector haxefmod-selector");
        var tab = el("div", "language-tab selected", labels[lang] || "Code");
        tab.setAttribute("data-language", lang || "language-all");
        selector.appendChild(tab);
        highlight.parentNode.insertBefore(selector, highlight);
        return selector;
    }

    // Every code location on the page is keyed by extension/keys.js, the
    // same way the catalog was built, and looked up by that key.
    function injectAll() {
        var root = document.querySelector("div.manual-content");
        if (!root || typeof haxefmodKeys === "undefined") return false;
        var units = haxefmodKeys.units(root);
        var examples = EXAMPLES[pageName()] || {};
        for (var i = 0; i < units.length; i++) {
            var unit = units[i];
            var node = unit.node;
            if (unit.added || node.dataset.haxefmod) continue;
            var block;
            if (unit.kind === "function") {
                block = renderBlock(DATA.entries[unit.key]);
            } else if (examples[unit.key]) {
                block = renderExample(examples[unit.key]);
            } else {
                continue;
            }
            var selector = unit.tabbed ? node : selectorForLone(node);
            if (addTab(selector, block)) node.dataset.haxefmod = "1";
        }
        return units.length > 0;
    }

    function setDisplay(selectorList, display) {
        var nodes = document.querySelectorAll(selectorList);
        for (var i = 0; i < nodes.length; i++) nodes[i].style.display = display;
    }

    function apply(selected) {
        var haxeOn = selected === LANG;
        setDisplay("." + LANG, haxeOn ? "block" : "none");
        var tabs = document.querySelectorAll(".language-tab");
        for (var i = 0; i < tabs.length; i++) {
            var lang = tabs[i].getAttribute("data-language");
            if (lang === LANG) tabs[i].classList.toggle("selected", haxeOn);
            else if (haxeOn) tabs[i].classList.remove("selected");
        }
        if (haxeOn) {
            setDisplay(NATIVE_LANGS.map(function (l) { return "." + l; }).join(", "), "none");
        }
    }

    function applyNative(lang) {
        var tabs = document.querySelectorAll(".language-tab");
        for (var i = 0; i < tabs.length; i++) {
            tabs[i].classList.toggle("selected", tabs[i].getAttribute("data-language") === lang);
        }
        NATIVE_LANGS.forEach(function (other) {
            setDisplay("." + other, other === lang ? "block" : "none");
        });
        try { window.localStorage.setItem(STORAGE_KEY, lang); } catch (e) { /* ignore */ }
    }

    function haxeChosen() {
        try { return window.localStorage.getItem(OWN_KEY) === "1"; } catch (e) { return false; }
    }

    function choose(haxe) {
        try {
            if (haxe) {
                window.localStorage.setItem(OWN_KEY, "1");
                window.localStorage.setItem(STORAGE_KEY, LANG);
            } else {
                window.localStorage.removeItem(OWN_KEY);
            }
        } catch (e) { /* storage unavailable, selection lasts for the page only */ }
    }

    // Swapping a language block changes the height below the tab strip,
    // and the browser's scroll anchoring then shifts the page so some
    // other element stays put. The tab that was clicked is what the eye
    // is on, so its viewport position is taken before any handler runs
    // (capture phase) and restored once the site and this script have
    // both applied the change.
    document.addEventListener("click", function (event) {
        var tab = event.target.closest ? event.target.closest(".language-tab") : null;
        if (!tab) return;
        var before = tab.getBoundingClientRect().top;
        window.requestAnimationFrame(function () {
            var after = tab.getBoundingClientRect().top;
            if (after !== before) window.scrollBy(0, after - before);
        });
    }, true);

    document.addEventListener("click", function (event) {
        var tab = event.target.closest ? event.target.closest(".language-tab") : null;
        if (!tab) return;
        var lang = tab.getAttribute("data-language");
        if (lang === LANG) {
            choose(true);
            apply(LANG);
        } else {
            choose(false);
            apply(lang);
            // The site only wired the tabs it rendered. Tabs on the
            // selectors added for lone examples do the same work here.
            if (tab.parentNode.classList.contains("haxefmod-selector")) applyNative(lang);
        }
    });

    var pending = false;
    function schedule() {
        if (pending) return;
        pending = true;
        window.requestAnimationFrame(function () {
            pending = false;
            if (injectAll() && haxeChosen()) {
                choose(true);
                apply(LANG);
                // The site's selector initializes after render and may
                // run later than this pass. Reapply once it has settled.
                window.setTimeout(function () { apply(LANG); }, 50);
            }
        });
    }

    new MutationObserver(schedule).observe(document.documentElement, { childList: true, subtree: true });
    schedule();
})();
