package haxefmod.core;

/*
 * Generated by ci/gen-dsp-parameters.py from fmod_dsp_effects.h.
 * Do not edit, rerun the script.
 *
 * The parameter indices of the built-in DSP effects, one enum per
 * effect. Each converts to Int, so dsp.setParameter(DspLowpass.CUTOFF, 800)
 * works with every Dsp parameter setter and getter. The values a
 * parameter accepts (pan modes, FFT windows) are in DspEnums.hx.
 */

/** FMOD_DSP_OSCILLATOR, parameter indices of the oscillator generator. */
enum abstract DspOscillator(Int) from Int to Int {
    var TYPE = 0;
    var RATE = 1;
}

/** FMOD_DSP_LOWPASS, parameter indices of the lowpass effect. */
enum abstract DspLowpass(Int) from Int to Int {
    var CUTOFF = 0;
    var RESONANCE = 1;
}

/** FMOD_DSP_ITLOWPASS, parameter indices of the IT lowpass effect. */
enum abstract DspItLowpass(Int) from Int to Int {
    var CUTOFF = 0;
    var RESONANCE = 1;
}

/** FMOD_DSP_HIGHPASS, parameter indices of the highpass effect. */
enum abstract DspHighpass(Int) from Int to Int {
    var CUTOFF = 0;
    var RESONANCE = 1;
}

/** FMOD_DSP_ECHO, parameter indices of the echo effect. */
enum abstract DspEcho(Int) from Int to Int {
    var DELAY = 0;
    var FEEDBACK = 1;
    var DRYLEVEL = 2;
    var WETLEVEL = 3;
    var DELAYCHANGEMODE = 4;
}

/** FMOD_DSP_FADER, parameter indices of the fader effect. */
enum abstract DspFader(Int) from Int to Int {
    var GAIN = 0;
    var OVERALL_GAIN = 1;
}

/** FMOD_DSP_FLANGE, parameter indices of the flange effect. */
enum abstract DspFlange(Int) from Int to Int {
    var MIX = 0;
    var DEPTH = 1;
    var RATE = 2;
}

/** FMOD_DSP_DISTORTION, parameter indices of the distortion effect. */
enum abstract DspDistortion(Int) from Int to Int {
    var LEVEL = 0;
}

/** FMOD_DSP_NORMALIZE, parameter indices of the normalize effect. */
enum abstract DspNormalize(Int) from Int to Int {
    var FADETIME = 0;
    var THRESHOLD = 1;
    var MAXAMP = 2;
}

/** FMOD_DSP_LIMITER, parameter indices of the limiter effect. */
enum abstract DspLimiter(Int) from Int to Int {
    var RELEASETIME = 0;
    var CEILING = 1;
    var MAXIMIZERGAIN = 2;
    var MODE = 3;
}

/** FMOD_DSP_PARAMEQ, parameter indices of the parametric EQ effect. */
enum abstract DspParamEq(Int) from Int to Int {
    var CENTER = 0;
    var BANDWIDTH = 1;
    var GAIN = 2;
}

/** FMOD_DSP_MULTIBAND_EQ, parameter indices of the multiband EQ effect. */
enum abstract DspMultibandEq(Int) from Int to Int {
    var A_FILTER = 0;
    var A_FREQUENCY = 1;
    var A_Q = 2;
    var A_GAIN = 3;
    var B_FILTER = 4;
    var B_FREQUENCY = 5;
    var B_Q = 6;
    var B_GAIN = 7;
    var C_FILTER = 8;
    var C_FREQUENCY = 9;
    var C_Q = 10;
    var C_GAIN = 11;
    var D_FILTER = 12;
    var D_FREQUENCY = 13;
    var D_Q = 14;
    var D_GAIN = 15;
    var E_FILTER = 16;
    var E_FREQUENCY = 17;
    var E_Q = 18;
    var E_GAIN = 19;
}

/** FMOD_DSP_MULTIBAND_DYNAMICS, parameter indices of the multiband dynamics effect. */
enum abstract DspMultibandDynamics(Int) from Int to Int {
    var LOWER_FREQUENCY = 0;
    var UPPER_FREQUENCY = 1;
    var LINKED = 2;
    var USE_SIDECHAIN = 3;
    var A_MODE = 4;
    var A_GAIN = 5;
    var A_THRESHOLD = 6;
    var A_RATIO = 7;
    var A_ATTACK = 8;
    var A_RELEASE = 9;
    var A_GAIN_MAKEUP = 10;
    var A_RESPONSE_DATA = 11;
    var B_MODE = 12;
    var B_GAIN = 13;
    var B_THRESHOLD = 14;
    var B_RATIO = 15;
    var B_ATTACK = 16;
    var B_RELEASE = 17;
    var B_GAIN_MAKEUP = 18;
    var B_RESPONSE_DATA = 19;
    var C_MODE = 20;
    var C_GAIN = 21;
    var C_THRESHOLD = 22;
    var C_RATIO = 23;
    var C_ATTACK = 24;
    var C_RELEASE = 25;
    var C_GAIN_MAKEUP = 26;
    var C_RESPONSE_DATA = 27;
}

/** FMOD_DSP_PITCHSHIFT, parameter indices of the pitch shift effect. */
enum abstract DspPitchShift(Int) from Int to Int {
    var PITCH = 0;
    var FFTSIZE = 1;
    var OVERLAP = 2;
    var MAXCHANNELS = 3;
}

/** FMOD_DSP_CHORUS, parameter indices of the chorus effect. */
enum abstract DspChorus(Int) from Int to Int {
    var MIX = 0;
    var RATE = 1;
    var DEPTH = 2;
}

/** FMOD_DSP_ITECHO, parameter indices of the IT echo effect. */
enum abstract DspItEcho(Int) from Int to Int {
    var WETDRYMIX = 0;
    var FEEDBACK = 1;
    var LEFTDELAY = 2;
    var RIGHTDELAY = 3;
    var PANDELAY = 4;
}

/** FMOD_DSP_COMPRESSOR, parameter indices of the compressor effect. */
enum abstract DspCompressor(Int) from Int to Int {
    var THRESHOLD = 0;
    var RATIO = 1;
    var ATTACK = 2;
    var RELEASE = 3;
    var GAINMAKEUP = 4;
    var USESIDECHAIN = 5;
    var LINKED = 6;
}

/** FMOD_DSP_SFXREVERB, parameter indices of the SFX reverb effect. */
enum abstract DspSfxReverb(Int) from Int to Int {
    var DECAYTIME = 0;
    var EARLYDELAY = 1;
    var LATEDELAY = 2;
    var HFREFERENCE = 3;
    var HFDECAYRATIO = 4;
    var DIFFUSION = 5;
    var DENSITY = 6;
    var LOWSHELFFREQUENCY = 7;
    var LOWSHELFGAIN = 8;
    var HIGHCUT = 9;
    var EARLYLATEMIX = 10;
    var WETLEVEL = 11;
    var DRYLEVEL = 12;
}

/** FMOD_DSP_LOWPASS_SIMPLE, parameter indices of the simple lowpass effect. */
enum abstract DspLowpassSimple(Int) from Int to Int {
    var CUTOFF = 0;
}

/** FMOD_DSP_DELAY, parameter indices of the delay effect. */
enum abstract DspDelay(Int) from Int to Int {
    var CH0 = 0;
    var CH1 = 1;
    var CH2 = 2;
    var CH3 = 3;
    var CH4 = 4;
    var CH5 = 5;
    var CH6 = 6;
    var CH7 = 7;
    var CH8 = 8;
    var CH9 = 9;
    var CH10 = 10;
    var CH11 = 11;
    var CH12 = 12;
    var CH13 = 13;
    var CH14 = 14;
    var CH15 = 15;
    var MAXDELAY = 16;
}

/** FMOD_DSP_TREMOLO, parameter indices of the tremolo effect. */
enum abstract DspTremolo(Int) from Int to Int {
    var FREQUENCY = 0;
    var DEPTH = 1;
    var SHAPE = 2;
    var SKEW = 3;
    var DUTY = 4;
    var SQUARE = 5;
    var PHASE = 6;
    var SPREAD = 7;
}

/** FMOD_DSP_SEND, parameter indices of the send effect. */
enum abstract DspSend(Int) from Int to Int {
    var RETURNID = 0;
    var LEVEL = 1;
}

/** FMOD_DSP_RETURN, parameter indices of the return effect. */
enum abstract DspReturn(Int) from Int to Int {
    var ID = 0;
    var INPUT_SPEAKER_MODE = 1;
}

/** FMOD_DSP_HIGHPASS_SIMPLE, parameter indices of the simple highpass effect. */
enum abstract DspHighpassSimple(Int) from Int to Int {
    var CUTOFF = 0;
}

/** FMOD_DSP_PAN, parameter indices of the pan effect. Names that start with a digit keep a leading underscore, since a Haxe identifier cannot start with one. */
enum abstract DspPan(Int) from Int to Int {
    var MODE = 0;
    var _2D_STEREO_POSITION = 1;
    var _2D_DIRECTION = 2;
    var _2D_EXTENT = 3;
    var _2D_ROTATION = 4;
    var _2D_LFE_LEVEL = 5;
    var _2D_STEREO_MODE = 6;
    var _2D_STEREO_SEPARATION = 7;
    var _2D_STEREO_AXIS = 8;
    var ENABLED_SPEAKERS = 9;
    var _3D_POSITION = 10;
    var _3D_ROLLOFF = 11;
    var _3D_MIN_DISTANCE = 12;
    var _3D_MAX_DISTANCE = 13;
    var _3D_EXTENT_MODE = 14;
    var _3D_SOUND_SIZE = 15;
    var _3D_MIN_EXTENT = 16;
    var _3D_PAN_BLEND = 17;
    var LFE_UPMIX_ENABLED = 18;
    var OVERALL_GAIN = 19;
    var SURROUND_SPEAKER_MODE = 20;
    var _2D_HEIGHT_BLEND = 21;
    var ATTENUATION_RANGE = 22;
    var OVERRIDE_RANGE = 23;
}

/** FMOD_DSP_THREE_EQ, parameter indices of the three band EQ effect. */
enum abstract DspThreeEq(Int) from Int to Int {
    var LOWGAIN = 0;
    var MIDGAIN = 1;
    var HIGHGAIN = 2;
    var LOWCROSSOVER = 3;
    var HIGHCROSSOVER = 4;
    var CROSSOVERSLOPE = 5;
}

/** FMOD_DSP_FFT, parameter indices of the FFT analyser. */
enum abstract DspFft(Int) from Int to Int {
    var WINDOWSIZE = 0;
    var WINDOW = 1;
    var BAND_START_FREQ = 2;
    var BAND_STOP_FREQ = 3;
    var SPECTRUMDATA = 4;
    var RMS = 5;
    var SPECTRAL_CENTROID = 6;
    var IMMEDIATE_MODE = 7;
    var DOWNMIX = 8;
    var CHANNEL = 9;
}

/** FMOD_DSP_LOUDNESS_METER, parameter indices of the loudness meter. */
enum abstract DspLoudnessMeter(Int) from Int to Int {
    var STATE = 0;
    var WEIGHTING = 1;
    var INFO = 2;
}

/** FMOD_DSP_CONVOLUTION_REVERB, parameter indices of the convolution reverb effect. */
enum abstract DspConvolutionReverb(Int) from Int to Int {
    var PARAM_IR = 0;
    var PARAM_WET = 1;
    var PARAM_DRY = 2;
    var PARAM_LINKED = 3;
}

/** FMOD_DSP_CHANNELMIX, parameter indices of the channel mix effect. */
enum abstract DspChannelMix(Int) from Int to Int {
    var OUTPUTGROUPING = 0;
    var GAIN_CH0 = 1;
    var GAIN_CH1 = 2;
    var GAIN_CH2 = 3;
    var GAIN_CH3 = 4;
    var GAIN_CH4 = 5;
    var GAIN_CH5 = 6;
    var GAIN_CH6 = 7;
    var GAIN_CH7 = 8;
    var GAIN_CH8 = 9;
    var GAIN_CH9 = 10;
    var GAIN_CH10 = 11;
    var GAIN_CH11 = 12;
    var GAIN_CH12 = 13;
    var GAIN_CH13 = 14;
    var GAIN_CH14 = 15;
    var GAIN_CH15 = 16;
    var GAIN_CH16 = 17;
    var GAIN_CH17 = 18;
    var GAIN_CH18 = 19;
    var GAIN_CH19 = 20;
    var GAIN_CH20 = 21;
    var GAIN_CH21 = 22;
    var GAIN_CH22 = 23;
    var GAIN_CH23 = 24;
    var GAIN_CH24 = 25;
    var GAIN_CH25 = 26;
    var GAIN_CH26 = 27;
    var GAIN_CH27 = 28;
    var GAIN_CH28 = 29;
    var GAIN_CH29 = 30;
    var GAIN_CH30 = 31;
    var GAIN_CH31 = 32;
    var OUTPUT_CH0 = 33;
    var OUTPUT_CH1 = 34;
    var OUTPUT_CH2 = 35;
    var OUTPUT_CH3 = 36;
    var OUTPUT_CH4 = 37;
    var OUTPUT_CH5 = 38;
    var OUTPUT_CH6 = 39;
    var OUTPUT_CH7 = 40;
    var OUTPUT_CH8 = 41;
    var OUTPUT_CH9 = 42;
    var OUTPUT_CH10 = 43;
    var OUTPUT_CH11 = 44;
    var OUTPUT_CH12 = 45;
    var OUTPUT_CH13 = 46;
    var OUTPUT_CH14 = 47;
    var OUTPUT_CH15 = 48;
    var OUTPUT_CH16 = 49;
    var OUTPUT_CH17 = 50;
    var OUTPUT_CH18 = 51;
    var OUTPUT_CH19 = 52;
    var OUTPUT_CH20 = 53;
    var OUTPUT_CH21 = 54;
    var OUTPUT_CH22 = 55;
    var OUTPUT_CH23 = 56;
    var OUTPUT_CH24 = 57;
    var OUTPUT_CH25 = 58;
    var OUTPUT_CH26 = 59;
    var OUTPUT_CH27 = 60;
    var OUTPUT_CH28 = 61;
    var OUTPUT_CH29 = 62;
    var OUTPUT_CH30 = 63;
    var OUTPUT_CH31 = 64;
}

/** FMOD_DSP_TRANSCEIVER, parameter indices of the transceiver effect. */
enum abstract DspTransceiver(Int) from Int to Int {
    var TRANSMIT = 0;
    var GAIN = 1;
    var CHANNEL = 2;
    var TRANSMITSPEAKERMODE = 3;
}

/** FMOD_DSP_OBJECTPAN, parameter indices of the object pan effect. Names that start with a digit keep a leading underscore, since a Haxe identifier cannot start with one. */
enum abstract DspObjectPan(Int) from Int to Int {
    var _3D_POSITION = 0;
    var _3D_ROLLOFF = 1;
    var _3D_MIN_DISTANCE = 2;
    var _3D_MAX_DISTANCE = 3;
    var _3D_EXTENT_MODE = 4;
    var _3D_SOUND_SIZE = 5;
    var _3D_MIN_EXTENT = 6;
    var OVERALL_GAIN = 7;
    var OUTPUTGAIN = 8;
    var ATTENUATION_RANGE = 9;
    var OVERRIDE_RANGE = 10;
}
