package haxefmod.studio;

/**
 * FMOD_RESULT error codes, pinned to the exact values from FMOD 2.03.12
 * fmod_common.h. Values are explicit so a reordered or extended native enum
 * can never silently shift meanings.
 */
enum abstract FmodResult(Int) from Int to Int {
    var FMOD_OK = 0;
    var FMOD_ERR_BADCOMMAND = 1;
    var FMOD_ERR_CHANNEL_ALLOC = 2;
    var FMOD_ERR_CHANNEL_STOLEN = 3;
    var FMOD_ERR_DMA = 4;
    var FMOD_ERR_DSP_CONNECTION = 5;
    var FMOD_ERR_DSP_DONTPROCESS = 6;
    var FMOD_ERR_DSP_FORMAT = 7;
    var FMOD_ERR_DSP_INUSE = 8;
    var FMOD_ERR_DSP_NOTFOUND = 9;
    var FMOD_ERR_DSP_RESERVED = 10;
    var FMOD_ERR_DSP_SILENCE = 11;
    var FMOD_ERR_DSP_TYPE = 12;
    var FMOD_ERR_FILE_BAD = 13;
    var FMOD_ERR_FILE_COULDNOTSEEK = 14;
    var FMOD_ERR_FILE_DISKEJECTED = 15;
    var FMOD_ERR_FILE_EOF = 16;
    var FMOD_ERR_FILE_ENDOFDATA = 17;
    var FMOD_ERR_FILE_NOTFOUND = 18;
    var FMOD_ERR_FORMAT = 19;
    var FMOD_ERR_HEADER_MISMATCH = 20;
    var FMOD_ERR_HTTP = 21;
    var FMOD_ERR_HTTP_ACCESS = 22;
    var FMOD_ERR_HTTP_PROXY_AUTH = 23;
    var FMOD_ERR_HTTP_SERVER_ERROR = 24;
    var FMOD_ERR_HTTP_TIMEOUT = 25;
    var FMOD_ERR_INITIALIZATION = 26;
    var FMOD_ERR_INITIALIZED = 27;
    var FMOD_ERR_INTERNAL = 28;
    var FMOD_ERR_INVALID_FLOAT = 29;
    var FMOD_ERR_INVALID_HANDLE = 30;
    var FMOD_ERR_INVALID_PARAM = 31;
    var FMOD_ERR_INVALID_POSITION = 32;
    var FMOD_ERR_INVALID_SPEAKER = 33;
    var FMOD_ERR_INVALID_SYNCPOINT = 34;
    var FMOD_ERR_INVALID_THREAD = 35;
    var FMOD_ERR_INVALID_VECTOR = 36;
    var FMOD_ERR_MAXAUDIBLE = 37;
    var FMOD_ERR_MEMORY = 38;
    var FMOD_ERR_MEMORY_CANTPOINT = 39;
    var FMOD_ERR_NEEDS3D = 40;
    var FMOD_ERR_NEEDSHARDWARE = 41;
    var FMOD_ERR_NET_CONNECT = 42;
    var FMOD_ERR_NET_SOCKET_ERROR = 43;
    var FMOD_ERR_NET_URL = 44;
    var FMOD_ERR_NET_WOULD_BLOCK = 45;
    var FMOD_ERR_NOTREADY = 46;
    var FMOD_ERR_OUTPUT_ALLOCATED = 47;
    var FMOD_ERR_OUTPUT_CREATEBUFFER = 48;
    var FMOD_ERR_OUTPUT_DRIVERCALL = 49;
    var FMOD_ERR_OUTPUT_FORMAT = 50;
    var FMOD_ERR_OUTPUT_INIT = 51;
    var FMOD_ERR_OUTPUT_NODRIVERS = 52;
    var FMOD_ERR_PLUGIN = 53;
    var FMOD_ERR_PLUGIN_MISSING = 54;
    var FMOD_ERR_PLUGIN_RESOURCE = 55;
    var FMOD_ERR_PLUGIN_VERSION = 56;
    var FMOD_ERR_RECORD = 57;
    var FMOD_ERR_REVERB_CHANNELGROUP = 58;
    var FMOD_ERR_REVERB_INSTANCE = 59;
    var FMOD_ERR_SUBSOUNDS = 60;
    var FMOD_ERR_SUBSOUND_ALLOCATED = 61;
    var FMOD_ERR_SUBSOUND_CANTMOVE = 62;
    var FMOD_ERR_TAGNOTFOUND = 63;
    var FMOD_ERR_TOOMANYCHANNELS = 64;
    var FMOD_ERR_TRUNCATED = 65;
    var FMOD_ERR_UNIMPLEMENTED = 66;
    var FMOD_ERR_UNINITIALIZED = 67;
    var FMOD_ERR_UNSUPPORTED = 68;
    var FMOD_ERR_VERSION = 69;
    var FMOD_ERR_EVENT_ALREADY_LOADED = 70;
    var FMOD_ERR_EVENT_LIVEUPDATE_BUSY = 71;
    var FMOD_ERR_EVENT_LIVEUPDATE_MISMATCH = 72;
    var FMOD_ERR_EVENT_LIVEUPDATE_TIMEOUT = 73;
    var FMOD_ERR_EVENT_NOTFOUND = 74;
    var FMOD_ERR_STUDIO_UNINITIALIZED = 75;
    var FMOD_ERR_STUDIO_NOT_LOADED = 76;
    var FMOD_ERR_INVALID_STRING = 77;
    var FMOD_ERR_ALREADY_LOCKED = 78;
    var FMOD_ERR_NOT_LOCKED = 79;
    var FMOD_ERR_RECORD_DISCONNECTED = 80;
    var FMOD_ERR_TOOMANYSAMPLES = 81;

    public inline function isOk():Bool {
        return this == 0;
    }

    public function toString():String {
        var name = names[this];
        return name != null ? name : 'FMOD_RESULT($this)';
    }

    static var names:Array<String> = [
        "FMOD_OK", "FMOD_ERR_BADCOMMAND", "FMOD_ERR_CHANNEL_ALLOC", "FMOD_ERR_CHANNEL_STOLEN",
        "FMOD_ERR_DMA", "FMOD_ERR_DSP_CONNECTION", "FMOD_ERR_DSP_DONTPROCESS", "FMOD_ERR_DSP_FORMAT",
        "FMOD_ERR_DSP_INUSE", "FMOD_ERR_DSP_NOTFOUND", "FMOD_ERR_DSP_RESERVED", "FMOD_ERR_DSP_SILENCE",
        "FMOD_ERR_DSP_TYPE", "FMOD_ERR_FILE_BAD", "FMOD_ERR_FILE_COULDNOTSEEK", "FMOD_ERR_FILE_DISKEJECTED",
        "FMOD_ERR_FILE_EOF", "FMOD_ERR_FILE_ENDOFDATA", "FMOD_ERR_FILE_NOTFOUND", "FMOD_ERR_FORMAT",
        "FMOD_ERR_HEADER_MISMATCH", "FMOD_ERR_HTTP", "FMOD_ERR_HTTP_ACCESS", "FMOD_ERR_HTTP_PROXY_AUTH",
        "FMOD_ERR_HTTP_SERVER_ERROR", "FMOD_ERR_HTTP_TIMEOUT", "FMOD_ERR_INITIALIZATION", "FMOD_ERR_INITIALIZED",
        "FMOD_ERR_INTERNAL", "FMOD_ERR_INVALID_FLOAT", "FMOD_ERR_INVALID_HANDLE", "FMOD_ERR_INVALID_PARAM",
        "FMOD_ERR_INVALID_POSITION", "FMOD_ERR_INVALID_SPEAKER", "FMOD_ERR_INVALID_SYNCPOINT", "FMOD_ERR_INVALID_THREAD",
        "FMOD_ERR_INVALID_VECTOR", "FMOD_ERR_MAXAUDIBLE", "FMOD_ERR_MEMORY", "FMOD_ERR_MEMORY_CANTPOINT",
        "FMOD_ERR_NEEDS3D", "FMOD_ERR_NEEDSHARDWARE", "FMOD_ERR_NET_CONNECT", "FMOD_ERR_NET_SOCKET_ERROR",
        "FMOD_ERR_NET_URL", "FMOD_ERR_NET_WOULD_BLOCK", "FMOD_ERR_NOTREADY", "FMOD_ERR_OUTPUT_ALLOCATED",
        "FMOD_ERR_OUTPUT_CREATEBUFFER", "FMOD_ERR_OUTPUT_DRIVERCALL", "FMOD_ERR_OUTPUT_FORMAT", "FMOD_ERR_OUTPUT_INIT",
        "FMOD_ERR_OUTPUT_NODRIVERS", "FMOD_ERR_PLUGIN", "FMOD_ERR_PLUGIN_MISSING", "FMOD_ERR_PLUGIN_RESOURCE",
        "FMOD_ERR_PLUGIN_VERSION", "FMOD_ERR_RECORD", "FMOD_ERR_REVERB_CHANNELGROUP", "FMOD_ERR_REVERB_INSTANCE",
        "FMOD_ERR_SUBSOUNDS", "FMOD_ERR_SUBSOUND_ALLOCATED", "FMOD_ERR_SUBSOUND_CANTMOVE", "FMOD_ERR_TAGNOTFOUND",
        "FMOD_ERR_TOOMANYCHANNELS", "FMOD_ERR_TRUNCATED", "FMOD_ERR_UNIMPLEMENTED", "FMOD_ERR_UNINITIALIZED",
        "FMOD_ERR_UNSUPPORTED", "FMOD_ERR_VERSION", "FMOD_ERR_EVENT_ALREADY_LOADED", "FMOD_ERR_EVENT_LIVEUPDATE_BUSY",
        "FMOD_ERR_EVENT_LIVEUPDATE_MISMATCH", "FMOD_ERR_EVENT_LIVEUPDATE_TIMEOUT", "FMOD_ERR_EVENT_NOTFOUND",
        "FMOD_ERR_STUDIO_UNINITIALIZED", "FMOD_ERR_STUDIO_NOT_LOADED", "FMOD_ERR_INVALID_STRING",
        "FMOD_ERR_ALREADY_LOCKED", "FMOD_ERR_NOT_LOCKED", "FMOD_ERR_RECORD_DISCONNECTED", "FMOD_ERR_TOOMANYSAMPLES"
    ];
}
