/* Generated by ci/haxe-enum-values.py from the Haxe enum sources.
 * Do not edit, rerun the script. */
#ifndef FAXE_HAXE_ENUMS_H
#define FAXE_HAXE_ENUMS_H

/* FmodStopMode mirrors FMOD_STUDIO_STOP_MODE */
#define FAXE_HX_FmodStopMode_ALLOWFADEOUT (0)
#define FAXE_HX_FmodStopMode_IMMEDIATE (1)
#define FAXE_HX_FmodStopMode_COUNT 2

/* FmodPlaybackState mirrors FMOD_STUDIO_PLAYBACK_STATE */
#define FAXE_HX_FmodPlaybackState_PLAYING (0)
#define FAXE_HX_FmodPlaybackState_SUSTAINING (1)
#define FAXE_HX_FmodPlaybackState_STOPPED (2)
#define FAXE_HX_FmodPlaybackState_STARTING (3)
#define FAXE_HX_FmodPlaybackState_STOPPING (4)
#define FAXE_HX_FmodPlaybackState_COUNT 5

/* FmodLoadingState mirrors FMOD_STUDIO_LOADING_STATE */
#define FAXE_HX_FmodLoadingState_UNLOADING (0)
#define FAXE_HX_FmodLoadingState_UNLOADED (1)
#define FAXE_HX_FmodLoadingState_LOADING (2)
#define FAXE_HX_FmodLoadingState_LOADED (3)
#define FAXE_HX_FmodLoadingState_ERROR (4)
#define FAXE_HX_FmodLoadingState_COUNT 5

/* FmodEventProperty mirrors FMOD_STUDIO_EVENT_PROPERTY */
#define FAXE_HX_FmodEventProperty_CHANNELPRIORITY (0)
#define FAXE_HX_FmodEventProperty_SCHEDULE_DELAY (1)
#define FAXE_HX_FmodEventProperty_SCHEDULE_LOOKAHEAD (2)
#define FAXE_HX_FmodEventProperty_MINIMUM_DISTANCE (3)
#define FAXE_HX_FmodEventProperty_MAXIMUM_DISTANCE (4)
#define FAXE_HX_FmodEventProperty_COOLDOWN (5)
#define FAXE_HX_FmodEventProperty_MAX (6)
#define FAXE_HX_FmodEventProperty_COUNT 7

/* FmodParameterType mirrors FMOD_STUDIO_PARAMETER_TYPE */
#define FAXE_HX_FmodParameterType_GAME_CONTROLLED (0)
#define FAXE_HX_FmodParameterType_AUTOMATIC_DISTANCE (1)
#define FAXE_HX_FmodParameterType_AUTOMATIC_EVENT_CONE_ANGLE (2)
#define FAXE_HX_FmodParameterType_AUTOMATIC_EVENT_ORIENTATION (3)
#define FAXE_HX_FmodParameterType_AUTOMATIC_DIRECTION (4)
#define FAXE_HX_FmodParameterType_AUTOMATIC_ELEVATION (5)
#define FAXE_HX_FmodParameterType_AUTOMATIC_LISTENER_ORIENTATION (6)
#define FAXE_HX_FmodParameterType_AUTOMATIC_SPEED (7)
#define FAXE_HX_FmodParameterType_AUTOMATIC_SPEED_ABSOLUTE (8)
#define FAXE_HX_FmodParameterType_AUTOMATIC_DISTANCE_NORMALIZED (9)
#define FAXE_HX_FmodParameterType_MAX (10)
#define FAXE_HX_FmodParameterType_COUNT 11

/* FmodParameterFlags mirrors FMOD_STUDIO_PARAMETER_FLAGS */
#define FAXE_HX_FmodParameterFlags_READONLY (0x00000001)
#define FAXE_HX_FmodParameterFlags_AUTOMATIC (0x00000002)
#define FAXE_HX_FmodParameterFlags_GLOBAL (0x00000004)
#define FAXE_HX_FmodParameterFlags_DISCRETE (0x00000008)
#define FAXE_HX_FmodParameterFlags_LABELED (0x00000010)
#define FAXE_HX_FmodParameterFlags_COUNT 5

/* FmodUserPropertyType mirrors FMOD_STUDIO_USER_PROPERTY_TYPE */
#define FAXE_HX_FmodUserPropertyType_INTEGER (0)
#define FAXE_HX_FmodUserPropertyType_BOOLEAN (1)
#define FAXE_HX_FmodUserPropertyType_FLOAT (2)
#define FAXE_HX_FmodUserPropertyType_STRING (3)
#define FAXE_HX_FmodUserPropertyType_COUNT 4

/* FmodLoadBankFlags mirrors FMOD_STUDIO_LOAD_BANK_FLAGS */
#define FAXE_HX_FmodLoadBankFlags_NORMAL (0)
#define FAXE_HX_FmodLoadBankFlags_NONBLOCKING (1)
#define FAXE_HX_FmodLoadBankFlags_DECOMPRESS_SAMPLES (2)
#define FAXE_HX_FmodLoadBankFlags_UNENCRYPTED (4)
#define FAXE_HX_FmodLoadBankFlags_COUNT 4

/* FmodPluginType mirrors FMOD_PLUGINTYPE */
#define FAXE_HX_FmodPluginType_OUTPUT (0)
#define FAXE_HX_FmodPluginType_CODEC (1)
#define FAXE_HX_FmodPluginType_DSP (2)
#define FAXE_HX_FmodPluginType_MAX (3)
#define FAXE_HX_FmodPluginType_COUNT 4

/* FmodTagType mirrors FMOD_TAGTYPE */
#define FAXE_HX_FmodTagType_UNKNOWN (0)
#define FAXE_HX_FmodTagType_ID3V1 (1)
#define FAXE_HX_FmodTagType_ID3V2 (2)
#define FAXE_HX_FmodTagType_VORBISCOMMENT (3)
#define FAXE_HX_FmodTagType_SHOUTCAST (4)
#define FAXE_HX_FmodTagType_ICECAST (5)
#define FAXE_HX_FmodTagType_ASF (6)
#define FAXE_HX_FmodTagType_MIDI (7)
#define FAXE_HX_FmodTagType_PLAYLIST (8)
#define FAXE_HX_FmodTagType_FMOD (9)
#define FAXE_HX_FmodTagType_USER (10)
#define FAXE_HX_FmodTagType_MAX (11)
#define FAXE_HX_FmodTagType_COUNT 12

/* FmodTagDataType mirrors FMOD_TAGDATATYPE */
#define FAXE_HX_FmodTagDataType_BINARY (0)
#define FAXE_HX_FmodTagDataType_INT (1)
#define FAXE_HX_FmodTagDataType_FLOAT (2)
#define FAXE_HX_FmodTagDataType_STRING (3)
#define FAXE_HX_FmodTagDataType_STRING_UTF16 (4)
#define FAXE_HX_FmodTagDataType_STRING_UTF16BE (5)
#define FAXE_HX_FmodTagDataType_STRING_UTF8 (6)
#define FAXE_HX_FmodTagDataType_MAX (7)
#define FAXE_HX_FmodTagDataType_COUNT 8

/* FmodSpeaker mirrors FMOD_SPEAKER */
#define FAXE_HX_FmodSpeaker_NONE (-1)
#define FAXE_HX_FmodSpeaker_FRONT_LEFT (0)
#define FAXE_HX_FmodSpeaker_FRONT_RIGHT (1)
#define FAXE_HX_FmodSpeaker_FRONT_CENTER (2)
#define FAXE_HX_FmodSpeaker_LOW_FREQUENCY (3)
#define FAXE_HX_FmodSpeaker_SURROUND_LEFT (4)
#define FAXE_HX_FmodSpeaker_SURROUND_RIGHT (5)
#define FAXE_HX_FmodSpeaker_BACK_LEFT (6)
#define FAXE_HX_FmodSpeaker_BACK_RIGHT (7)
#define FAXE_HX_FmodSpeaker_TOP_FRONT_LEFT (8)
#define FAXE_HX_FmodSpeaker_TOP_FRONT_RIGHT (9)
#define FAXE_HX_FmodSpeaker_TOP_BACK_LEFT (10)
#define FAXE_HX_FmodSpeaker_TOP_BACK_RIGHT (11)
#define FAXE_HX_FmodSpeaker_MAX (12)
#define FAXE_HX_FmodSpeaker_COUNT 14

/* FmodSpeakerMode mirrors FMOD_SPEAKERMODE */
#define FAXE_HX_FmodSpeakerMode_DEFAULT (0)
#define FAXE_HX_FmodSpeakerMode_RAW (1)
#define FAXE_HX_FmodSpeakerMode_MONO (2)
#define FAXE_HX_FmodSpeakerMode_STEREO (3)
#define FAXE_HX_FmodSpeakerMode_QUAD (4)
#define FAXE_HX_FmodSpeakerMode_SURROUND (5)
#define FAXE_HX_FmodSpeakerMode__5POINT1 (6)
#define FAXE_HX_FmodSpeakerMode__7POINT1 (7)
#define FAXE_HX_FmodSpeakerMode__7POINT1POINT4 (8)
#define FAXE_HX_FmodSpeakerMode_MAX (9)
#define FAXE_HX_FmodSpeakerMode_COUNT 10

/* FmodOutputType mirrors FMOD_OUTPUTTYPE */
#define FAXE_HX_FmodOutputType_AUTODETECT (0)
#define FAXE_HX_FmodOutputType_UNKNOWN (1)
#define FAXE_HX_FmodOutputType_NOSOUND (2)
#define FAXE_HX_FmodOutputType_WAVWRITER (3)
#define FAXE_HX_FmodOutputType_NOSOUND_NRT (4)
#define FAXE_HX_FmodOutputType_WAVWRITER_NRT (5)
#define FAXE_HX_FmodOutputType_WASAPI (6)
#define FAXE_HX_FmodOutputType_ASIO (7)
#define FAXE_HX_FmodOutputType_PULSEAUDIO (8)
#define FAXE_HX_FmodOutputType_ALSA (9)
#define FAXE_HX_FmodOutputType_COREAUDIO (10)
#define FAXE_HX_FmodOutputType_AUDIOTRACK (11)
#define FAXE_HX_FmodOutputType_OPENSL (12)
#define FAXE_HX_FmodOutputType_AUDIOOUT (13)
#define FAXE_HX_FmodOutputType_AUDIO3D (14)
#define FAXE_HX_FmodOutputType_WEBAUDIO (15)
#define FAXE_HX_FmodOutputType_NNAUDIO (16)
#define FAXE_HX_FmodOutputType_WINSONIC (17)
#define FAXE_HX_FmodOutputType_AAUDIO (18)
#define FAXE_HX_FmodOutputType_AUDIOWORKLET (19)
#define FAXE_HX_FmodOutputType_PHASE (20)
#define FAXE_HX_FmodOutputType_OHAUDIO (21)
#define FAXE_HX_FmodOutputType_MAX (22)
#define FAXE_HX_FmodOutputType_COUNT 23

/* FmodDriverState mirrors FMOD_DRIVER_STATE */
#define FAXE_HX_FmodDriverState_CONNECTED (0x00000001)
#define FAXE_HX_FmodDriverState_DEFAULT (0x00000002)
#define FAXE_HX_FmodDriverState_COUNT 2

/* FmodChannelMask mirrors FMOD_CHANNELMASK */
#define FAXE_HX_FmodChannelMask_FRONT_LEFT (0x00000001)
#define FAXE_HX_FmodChannelMask_FRONT_RIGHT (0x00000002)
#define FAXE_HX_FmodChannelMask_FRONT_CENTER (0x00000004)
#define FAXE_HX_FmodChannelMask_LOW_FREQUENCY (0x00000008)
#define FAXE_HX_FmodChannelMask_SURROUND_LEFT (0x00000010)
#define FAXE_HX_FmodChannelMask_SURROUND_RIGHT (0x00000020)
#define FAXE_HX_FmodChannelMask_BACK_LEFT (0x00000040)
#define FAXE_HX_FmodChannelMask_BACK_RIGHT (0x00000080)
#define FAXE_HX_FmodChannelMask_BACK_CENTER (0x00000100)
#define FAXE_HX_FmodChannelMask_MONO (0x00000001)
#define FAXE_HX_FmodChannelMask_STEREO (0x00000003)
#define FAXE_HX_FmodChannelMask_LRC (0x00000007)
#define FAXE_HX_FmodChannelMask_QUAD (0x00000033)
#define FAXE_HX_FmodChannelMask_SURROUND (0x00000037)
#define FAXE_HX_FmodChannelMask__5POINT1 (0x0000003F)
#define FAXE_HX_FmodChannelMask__5POINT1_REARS (0x000000CF)
#define FAXE_HX_FmodChannelMask__7POINT0 (0x000000F7)
#define FAXE_HX_FmodChannelMask__7POINT1 (0x000000FF)
#define FAXE_HX_FmodChannelMask_COUNT 18

/* FmodTimeUnit mirrors FMOD_TIMEUNIT */
#define FAXE_HX_FmodTimeUnit_MS (0x00000001)
#define FAXE_HX_FmodTimeUnit_PCM (0x00000002)
#define FAXE_HX_FmodTimeUnit_PCMBYTES (0x00000004)
#define FAXE_HX_FmodTimeUnit_RAWBYTES (0x00000008)
#define FAXE_HX_FmodTimeUnit_PCMFRACTION (0x00000010)
#define FAXE_HX_FmodTimeUnit_MODORDER (0x00000100)
#define FAXE_HX_FmodTimeUnit_MODROW (0x00000200)
#define FAXE_HX_FmodTimeUnit_MODPATTERN (0x00000400)
#define FAXE_HX_FmodTimeUnit_COUNT 8

/* FmodOpenState mirrors FMOD_OPENSTATE */
#define FAXE_HX_FmodOpenState_READY (0)
#define FAXE_HX_FmodOpenState_LOADING (1)
#define FAXE_HX_FmodOpenState_ERROR (2)
#define FAXE_HX_FmodOpenState_CONNECTING (3)
#define FAXE_HX_FmodOpenState_BUFFERING (4)
#define FAXE_HX_FmodOpenState_SEEKING (5)
#define FAXE_HX_FmodOpenState_PLAYING (6)
#define FAXE_HX_FmodOpenState_SETPOSITION (7)
#define FAXE_HX_FmodOpenState_MAX (8)
#define FAXE_HX_FmodOpenState_COUNT 9

/* FmodSoundType mirrors FMOD_SOUND_TYPE */
#define FAXE_HX_FmodSoundType_UNKNOWN (0)
#define FAXE_HX_FmodSoundType_AIFF (1)
#define FAXE_HX_FmodSoundType_ASF (2)
#define FAXE_HX_FmodSoundType_DLS (3)
#define FAXE_HX_FmodSoundType_FLAC (4)
#define FAXE_HX_FmodSoundType_FSB (5)
#define FAXE_HX_FmodSoundType_IT (6)
#define FAXE_HX_FmodSoundType_MIDI (7)
#define FAXE_HX_FmodSoundType_MOD (8)
#define FAXE_HX_FmodSoundType_MPEG (9)
#define FAXE_HX_FmodSoundType_OGGVORBIS (10)
#define FAXE_HX_FmodSoundType_PLAYLIST (11)
#define FAXE_HX_FmodSoundType_RAW (12)
#define FAXE_HX_FmodSoundType_S3M (13)
#define FAXE_HX_FmodSoundType_USER (14)
#define FAXE_HX_FmodSoundType_WAV (15)
#define FAXE_HX_FmodSoundType_XM (16)
#define FAXE_HX_FmodSoundType_XMA (17)
#define FAXE_HX_FmodSoundType_AUDIOQUEUE (18)
#define FAXE_HX_FmodSoundType_AT9 (19)
#define FAXE_HX_FmodSoundType_VORBIS (20)
#define FAXE_HX_FmodSoundType_MEDIA_FOUNDATION (21)
#define FAXE_HX_FmodSoundType_MEDIACODEC (22)
#define FAXE_HX_FmodSoundType_FADPCM (23)
#define FAXE_HX_FmodSoundType_OPUS (24)
#define FAXE_HX_FmodSoundType_MAX (25)
#define FAXE_HX_FmodSoundType_COUNT 26

/* FmodSoundFormat mirrors FMOD_SOUND_FORMAT */
#define FAXE_HX_FmodSoundFormat_NONE (0)
#define FAXE_HX_FmodSoundFormat_PCM8 (1)
#define FAXE_HX_FmodSoundFormat_PCM16 (2)
#define FAXE_HX_FmodSoundFormat_PCM24 (3)
#define FAXE_HX_FmodSoundFormat_PCM32 (4)
#define FAXE_HX_FmodSoundFormat_PCMFLOAT (5)
#define FAXE_HX_FmodSoundFormat_BITSTREAM (6)
#define FAXE_HX_FmodSoundFormat_MAX (7)
#define FAXE_HX_FmodSoundFormat_COUNT 8

/* FmodStudioInstanceType mirrors FMOD_STUDIO_INSTANCETYPE */
#define FAXE_HX_FmodStudioInstanceType_NONE (0)
#define FAXE_HX_FmodStudioInstanceType_SYSTEM (1)
#define FAXE_HX_FmodStudioInstanceType_EVENTDESCRIPTION (2)
#define FAXE_HX_FmodStudioInstanceType_EVENTINSTANCE (3)
#define FAXE_HX_FmodStudioInstanceType_PARAMETERINSTANCE (4)
#define FAXE_HX_FmodStudioInstanceType_BUS (5)
#define FAXE_HX_FmodStudioInstanceType_VCA (6)
#define FAXE_HX_FmodStudioInstanceType_BANK (7)
#define FAXE_HX_FmodStudioInstanceType_COMMANDREPLAY (8)
#define FAXE_HX_FmodStudioInstanceType_COUNT 9

/* DspConnectionType mirrors FMOD_DSPCONNECTION_TYPE */
#define FAXE_HX_DspConnectionType_STANDARD (0)
#define FAXE_HX_DspConnectionType_SIDECHAIN (1)
#define FAXE_HX_DspConnectionType_SEND (2)
#define FAXE_HX_DspConnectionType_SEND_SIDECHAIN (3)
#define FAXE_HX_DspConnectionType_PREALLOCATED (4)
#define FAXE_HX_DspConnectionType_MAX (5)
#define FAXE_HX_DspConnectionType_COUNT 6

/* SoundGroupBehavior mirrors FMOD_SOUNDGROUP_BEHAVIOR */
#define FAXE_HX_SoundGroupBehavior_FAIL (0)
#define FAXE_HX_SoundGroupBehavior_MUTE (1)
#define FAXE_HX_SoundGroupBehavior_STEALLOWEST (2)
#define FAXE_HX_SoundGroupBehavior_MAX (3)
#define FAXE_HX_SoundGroupBehavior_COUNT 4

/* ChannelControlDspIndex mirrors FMOD_CHANNELCONTROL_DSP_INDEX */
#define FAXE_HX_ChannelControlDspIndex_HEAD (-1)
#define FAXE_HX_ChannelControlDspIndex_FADER (-2)
#define FAXE_HX_ChannelControlDspIndex_TAIL (-3)
#define FAXE_HX_ChannelControlDspIndex_COUNT 3

/* FmodChannelControlType mirrors FMOD_CHANNELCONTROL_TYPE */
#define FAXE_HX_FmodChannelControlType_CHANNEL (0)
#define FAXE_HX_FmodChannelControlType_CHANNELGROUP (1)
#define FAXE_HX_FmodChannelControlType_MAX (2)
#define FAXE_HX_FmodChannelControlType_COUNT 3

/* FmodChannelControlCallbackType mirrors FMOD_CHANNELCONTROL_CALLBACK_TYPE */
#define FAXE_HX_FmodChannelControlCallbackType_END (0)
#define FAXE_HX_FmodChannelControlCallbackType_VIRTUALVOICE (1)
#define FAXE_HX_FmodChannelControlCallbackType_SYNCPOINT (2)
#define FAXE_HX_FmodChannelControlCallbackType_OCCLUSION (3)
#define FAXE_HX_FmodChannelControlCallbackType_MAX (4)
#define FAXE_HX_FmodChannelControlCallbackType_COUNT 5

/* FmodChannelOrder mirrors FMOD_CHANNELORDER */
#define FAXE_HX_FmodChannelOrder_DEFAULT (0)
#define FAXE_HX_FmodChannelOrder_WAVEFORMAT (1)
#define FAXE_HX_FmodChannelOrder_PROTOOLS (2)
#define FAXE_HX_FmodChannelOrder_ALLMONO (3)
#define FAXE_HX_FmodChannelOrder_ALLSTEREO (4)
#define FAXE_HX_FmodChannelOrder_ALSA (5)
#define FAXE_HX_FmodChannelOrder_MAX (6)
#define FAXE_HX_FmodChannelOrder_COUNT 7

/* FmodDebugFlags mirrors FMOD_DEBUG_FLAGS */
#define FAXE_HX_FmodDebugFlags_LEVEL_NONE (0x00000000)
#define FAXE_HX_FmodDebugFlags_LEVEL_ERROR (0x00000001)
#define FAXE_HX_FmodDebugFlags_LEVEL_WARNING (0x00000002)
#define FAXE_HX_FmodDebugFlags_LEVEL_LOG (0x00000004)
#define FAXE_HX_FmodDebugFlags_TYPE_MEMORY (0x00000100)
#define FAXE_HX_FmodDebugFlags_TYPE_FILE (0x00000200)
#define FAXE_HX_FmodDebugFlags_TYPE_CODEC (0x00000400)
#define FAXE_HX_FmodDebugFlags_TYPE_TRACE (0x00000800)
#define FAXE_HX_FmodDebugFlags_TYPE_VIRTUAL (0x00001000)
#define FAXE_HX_FmodDebugFlags_DISPLAY_TIMESTAMPS (0x00010000)
#define FAXE_HX_FmodDebugFlags_DISPLAY_LINENUMBERS (0x00020000)
#define FAXE_HX_FmodDebugFlags_DISPLAY_THREAD (0x00040000)
#define FAXE_HX_FmodDebugFlags_COUNT 12

/* FmodDebugMode mirrors FMOD_DEBUG_MODE */
#define FAXE_HX_FmodDebugMode_TTY (0)
#define FAXE_HX_FmodDebugMode_FILE (1)
#define FAXE_HX_FmodDebugMode_CALLBACK (2)
#define FAXE_HX_FmodDebugMode_COUNT 3

/* FmodInitFlags mirrors FMOD_INITFLAGS */
#define FAXE_HX_FmodInitFlags_NORMAL (0x00000000)
#define FAXE_HX_FmodInitFlags_STREAM_FROM_UPDATE (0x00000001)
#define FAXE_HX_FmodInitFlags_MIX_FROM_UPDATE (0x00000002)
#define FAXE_HX_FmodInitFlags__3D_RIGHTHANDED (0x00000004)
#define FAXE_HX_FmodInitFlags_CLIP_OUTPUT (0x00000008)
#define FAXE_HX_FmodInitFlags_CHANNEL_LOWPASS (0x00000100)
#define FAXE_HX_FmodInitFlags_CHANNEL_DISTANCEFILTER (0x00000200)
#define FAXE_HX_FmodInitFlags_PROFILE_ENABLE (0x00010000)
#define FAXE_HX_FmodInitFlags_VOL0_BECOMES_VIRTUAL (0x00020000)
#define FAXE_HX_FmodInitFlags_GEOMETRY_USECLOSEST (0x00040000)
#define FAXE_HX_FmodInitFlags_PREFER_DOLBY_DOWNMIX (0x00080000)
#define FAXE_HX_FmodInitFlags_THREAD_UNSAFE (0x00100000)
#define FAXE_HX_FmodInitFlags_PROFILE_METER_ALL (0x00200000)
#define FAXE_HX_FmodInitFlags_MEMORY_TRACKING (0x00400000)
#define FAXE_HX_FmodInitFlags_COUNT 14

/* FmodStudioInitFlags mirrors FMOD_STUDIO_INITFLAGS */
#define FAXE_HX_FmodStudioInitFlags_NORMAL (0x00000000)
#define FAXE_HX_FmodStudioInitFlags_LIVEUPDATE (0x00000001)
#define FAXE_HX_FmodStudioInitFlags_ALLOW_MISSING_PLUGINS (0x00000002)
#define FAXE_HX_FmodStudioInitFlags_SYNCHRONOUS_UPDATE (0x00000004)
#define FAXE_HX_FmodStudioInitFlags_DEFERRED_CALLBACKS (0x00000008)
#define FAXE_HX_FmodStudioInitFlags_LOAD_FROM_UPDATE (0x00000010)
#define FAXE_HX_FmodStudioInitFlags_MEMORY_TRACKING (0x00000020)
#define FAXE_HX_FmodStudioInitFlags_COUNT 7

/* FmodLoadMemoryMode mirrors FMOD_STUDIO_LOAD_MEMORY_MODE */
#define FAXE_HX_FmodLoadMemoryMode_MEMORY (0)
#define FAXE_HX_FmodLoadMemoryMode_MEMORY_POINT (1)
#define FAXE_HX_FmodLoadMemoryMode_COUNT 2

/* FmodCommandCaptureFlags mirrors FMOD_STUDIO_COMMANDCAPTURE_FLAGS */
#define FAXE_HX_FmodCommandCaptureFlags_NORMAL (0x00000000)
#define FAXE_HX_FmodCommandCaptureFlags_FILEFLUSH (0x00000001)
#define FAXE_HX_FmodCommandCaptureFlags_SKIP_INITIAL_STATE (0x00000002)
#define FAXE_HX_FmodCommandCaptureFlags_COUNT 3

/* FmodCommandReplayFlags mirrors FMOD_STUDIO_COMMANDREPLAY_FLAGS */
#define FAXE_HX_FmodCommandReplayFlags_NORMAL (0x00000000)
#define FAXE_HX_FmodCommandReplayFlags_SKIP_CLEANUP (0x00000001)
#define FAXE_HX_FmodCommandReplayFlags_FAST_FORWARD (0x00000002)
#define FAXE_HX_FmodCommandReplayFlags_SKIP_BANK_LOAD (0x00000004)
#define FAXE_HX_FmodCommandReplayFlags_COUNT 4

/* FmodMemoryType mirrors FMOD_MEMORY_TYPE */
#define FAXE_HX_FmodMemoryType_NORMAL (0x00000000)
#define FAXE_HX_FmodMemoryType_STREAM_FILE (0x00000001)
#define FAXE_HX_FmodMemoryType_STREAM_DECODE (0x00000002)
#define FAXE_HX_FmodMemoryType_SAMPLEDATA (0x00000004)
#define FAXE_HX_FmodMemoryType_DSP_BUFFER (0x00000008)
#define FAXE_HX_FmodMemoryType_PLUGIN (0x00000010)
#define FAXE_HX_FmodMemoryType_PERSISTENT (0x00200000)
#define FAXE_HX_FmodMemoryType_ALL (0xFFFFFFFF)
#define FAXE_HX_FmodMemoryType_COUNT 8

/* FmodThreadType mirrors FMOD_THREAD_TYPE */
#define FAXE_HX_FmodThreadType_MIXER (0)
#define FAXE_HX_FmodThreadType_FEEDER (1)
#define FAXE_HX_FmodThreadType_STREAM (2)
#define FAXE_HX_FmodThreadType_FILE (3)
#define FAXE_HX_FmodThreadType_NONBLOCKING (4)
#define FAXE_HX_FmodThreadType_RECORD (5)
#define FAXE_HX_FmodThreadType_GEOMETRY (6)
#define FAXE_HX_FmodThreadType_PROFILER (7)
#define FAXE_HX_FmodThreadType_STUDIO_UPDATE (8)
#define FAXE_HX_FmodThreadType_STUDIO_LOAD_BANK (9)
#define FAXE_HX_FmodThreadType_STUDIO_LOAD_SAMPLE (10)
#define FAXE_HX_FmodThreadType_CONVOLUTION1 (11)
#define FAXE_HX_FmodThreadType_CONVOLUTION2 (12)
#define FAXE_HX_FmodThreadType_MAX (13)
#define FAXE_HX_FmodThreadType_COUNT 14

/* FmodThreadPriority mirrors FMOD_THREAD_PRIORITY */
#define FAXE_HX_FmodThreadPriority_PLATFORM_MIN (-32768)
#define FAXE_HX_FmodThreadPriority_PLATFORM_MAX (32768)
#define FAXE_HX_FmodThreadPriority_DEFAULT (-32769)
#define FAXE_HX_FmodThreadPriority_LOW (-32770)
#define FAXE_HX_FmodThreadPriority_MEDIUM (-32771)
#define FAXE_HX_FmodThreadPriority_HIGH (-32772)
#define FAXE_HX_FmodThreadPriority_VERY_HIGH (-32773)
#define FAXE_HX_FmodThreadPriority_EXTREME (-32774)
#define FAXE_HX_FmodThreadPriority_CRITICAL (-32775)
#define FAXE_HX_FmodThreadPriority_MIXER (-32774)
#define FAXE_HX_FmodThreadPriority_FEEDER (-32775)
#define FAXE_HX_FmodThreadPriority_STREAM (-32773)
#define FAXE_HX_FmodThreadPriority_FILE (-32772)
#define FAXE_HX_FmodThreadPriority_NONBLOCKING (-32772)
#define FAXE_HX_FmodThreadPriority_RECORD (-32772)
#define FAXE_HX_FmodThreadPriority_GEOMETRY (-32770)
#define FAXE_HX_FmodThreadPriority_PROFILER (-32771)
#define FAXE_HX_FmodThreadPriority_STUDIO_UPDATE (-32771)
#define FAXE_HX_FmodThreadPriority_STUDIO_LOAD_BANK (-32771)
#define FAXE_HX_FmodThreadPriority_STUDIO_LOAD_SAMPLE (-32771)
#define FAXE_HX_FmodThreadPriority_CONVOLUTION1 (-32773)
#define FAXE_HX_FmodThreadPriority_CONVOLUTION2 (-32773)
#define FAXE_HX_FmodThreadPriority_COUNT 22

/* FmodThreadStackSize mirrors FMOD_THREAD_STACK_SIZE */
#define FAXE_HX_FmodThreadStackSize_DEFAULT (0)
#define FAXE_HX_FmodThreadStackSize_MIXER (81920)
#define FAXE_HX_FmodThreadStackSize_FEEDER (16384)
#define FAXE_HX_FmodThreadStackSize_STREAM (98304)
#define FAXE_HX_FmodThreadStackSize_FILE (65536)
#define FAXE_HX_FmodThreadStackSize_NONBLOCKING (114688)
#define FAXE_HX_FmodThreadStackSize_RECORD (16384)
#define FAXE_HX_FmodThreadStackSize_GEOMETRY (49152)
#define FAXE_HX_FmodThreadStackSize_PROFILER (131072)
#define FAXE_HX_FmodThreadStackSize_STUDIO_UPDATE (98304)
#define FAXE_HX_FmodThreadStackSize_STUDIO_LOAD_BANK (98304)
#define FAXE_HX_FmodThreadStackSize_STUDIO_LOAD_SAMPLE (98304)
#define FAXE_HX_FmodThreadStackSize_CONVOLUTION1 (16384)
#define FAXE_HX_FmodThreadStackSize_CONVOLUTION2 (16384)
#define FAXE_HX_FmodThreadStackSize_COUNT 14

/* FmodThreadAffinity mirrors FMOD_THREAD_AFFINITY */
#define FAXE_HX_FmodThreadAffinity_CORE_ALL (0)
#define FAXE_HX_FmodThreadAffinity_CORE_0 (0x00000001)
#define FAXE_HX_FmodThreadAffinity_CORE_1 (0x00000002)
#define FAXE_HX_FmodThreadAffinity_CORE_2 (0x00000004)
#define FAXE_HX_FmodThreadAffinity_CORE_3 (0x00000008)
#define FAXE_HX_FmodThreadAffinity_CORE_4 (0x00000010)
#define FAXE_HX_FmodThreadAffinity_CORE_5 (0x00000020)
#define FAXE_HX_FmodThreadAffinity_CORE_6 (0x00000040)
#define FAXE_HX_FmodThreadAffinity_CORE_7 (0x00000080)
#define FAXE_HX_FmodThreadAffinity_CORE_8 (0x00000100)
#define FAXE_HX_FmodThreadAffinity_CORE_9 (0x00000200)
#define FAXE_HX_FmodThreadAffinity_CORE_10 (0x00000400)
#define FAXE_HX_FmodThreadAffinity_CORE_11 (0x00000800)
#define FAXE_HX_FmodThreadAffinity_CORE_12 (0x00001000)
#define FAXE_HX_FmodThreadAffinity_CORE_13 (0x00002000)
#define FAXE_HX_FmodThreadAffinity_CORE_14 (0x00004000)
#define FAXE_HX_FmodThreadAffinity_CORE_15 (0x00008000)
#define FAXE_HX_FmodThreadAffinity_COUNT 17

/* FmodPortIndex mirrors FMOD_PORT_INDEX */
#define FAXE_HX_FmodPortIndex_NONE (-1)
#define FAXE_HX_FmodPortIndex_COUNT 1

/* FmodDspResampler mirrors FMOD_DSP_RESAMPLER */
#define FAXE_HX_FmodDspResampler_DEFAULT (0)
#define FAXE_HX_FmodDspResampler_NOINTERP (1)
#define FAXE_HX_FmodDspResampler_LINEAR (2)
#define FAXE_HX_FmodDspResampler_CUBIC (3)
#define FAXE_HX_FmodDspResampler_SPLINE (4)
#define FAXE_HX_FmodDspResampler_MAX (5)
#define FAXE_HX_FmodDspResampler_COUNT 6

/* FmodDspParameterType mirrors FMOD_DSP_PARAMETER_TYPE */
#define FAXE_HX_FmodDspParameterType_FLOAT (0)
#define FAXE_HX_FmodDspParameterType_INT (1)
#define FAXE_HX_FmodDspParameterType_BOOL (2)
#define FAXE_HX_FmodDspParameterType_DATA (3)
#define FAXE_HX_FmodDspParameterType_MAX (4)
#define FAXE_HX_FmodDspParameterType_COUNT 5

/* FmodDspParameterDataType mirrors FMOD_DSP_PARAMETER_DATA_TYPE */
#define FAXE_HX_FmodDspParameterDataType_USER (0)
#define FAXE_HX_FmodDspParameterDataType_OVERALLGAIN (-1)
#define FAXE_HX_FmodDspParameterDataType__3DATTRIBUTES (-2)
#define FAXE_HX_FmodDspParameterDataType_SIDECHAIN (-3)
#define FAXE_HX_FmodDspParameterDataType_FFT (-4)
#define FAXE_HX_FmodDspParameterDataType__3DATTRIBUTES_MULTI (-5)
#define FAXE_HX_FmodDspParameterDataType_ATTENUATION_RANGE (-6)
#define FAXE_HX_FmodDspParameterDataType_DYNAMIC_RESPONSE (-7)
#define FAXE_HX_FmodDspParameterDataType_FINITE_LENGTH (-8)
#define FAXE_HX_FmodDspParameterDataType_COUNT 9

/* FmodDspParameterFloatMappingType mirrors FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE */
#define FAXE_HX_FmodDspParameterFloatMappingType_LINEAR (0)
#define FAXE_HX_FmodDspParameterFloatMappingType_AUTO (1)
#define FAXE_HX_FmodDspParameterFloatMappingType_PIECEWISE_LINEAR (2)
#define FAXE_HX_FmodDspParameterFloatMappingType_COUNT 3

/* FmodDspProcessOperation mirrors FMOD_DSP_PROCESS_OPERATION */
#define FAXE_HX_FmodDspProcessOperation_PERFORM (0)
#define FAXE_HX_FmodDspProcessOperation_QUERY (1)
#define FAXE_HX_FmodDspProcessOperation_COUNT 2

/* FmodDspCallbackType mirrors FMOD_DSP_CALLBACK_TYPE */
#define FAXE_HX_FmodDspCallbackType_DATAPARAMETERRELEASE (0)
#define FAXE_HX_FmodDspCallbackType_MAX (1)
#define FAXE_HX_FmodDspCallbackType_COUNT 2

/* FmodDspPanSurroundFlags mirrors FMOD_DSP_PAN_SURROUND_FLAGS */
#define FAXE_HX_FmodDspPanSurroundFlags_DEFAULT (0)
#define FAXE_HX_FmodDspPanSurroundFlags_ROTATION_NOT_BIASED (1)
#define FAXE_HX_FmodDspPanSurroundFlags_COUNT 2

/* FmodErrorCallbackInstanceType mirrors FMOD_ERRORCALLBACK_INSTANCETYPE */
#define FAXE_HX_FmodErrorCallbackInstanceType_NONE (0)
#define FAXE_HX_FmodErrorCallbackInstanceType_SYSTEM (1)
#define FAXE_HX_FmodErrorCallbackInstanceType_CHANNEL (2)
#define FAXE_HX_FmodErrorCallbackInstanceType_CHANNELGROUP (3)
#define FAXE_HX_FmodErrorCallbackInstanceType_CHANNELCONTROL (4)
#define FAXE_HX_FmodErrorCallbackInstanceType_SOUND (5)
#define FAXE_HX_FmodErrorCallbackInstanceType_SOUNDGROUP (6)
#define FAXE_HX_FmodErrorCallbackInstanceType_DSP (7)
#define FAXE_HX_FmodErrorCallbackInstanceType_DSPCONNECTION (8)
#define FAXE_HX_FmodErrorCallbackInstanceType_GEOMETRY (9)
#define FAXE_HX_FmodErrorCallbackInstanceType_REVERB3D (10)
#define FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_SYSTEM (11)
#define FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_EVENTDESCRIPTION (12)
#define FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_EVENTINSTANCE (13)
#define FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_PARAMETERINSTANCE (14)
#define FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_BUS (15)
#define FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_VCA (16)
#define FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_BANK (17)
#define FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_COMMANDREPLAY (18)
#define FAXE_HX_FmodErrorCallbackInstanceType_COUNT 19

/* FmodPortType mirrors FMOD_PORT_TYPE */
#define FAXE_HX_FmodPortType_MUSIC (0)
#define FAXE_HX_FmodPortType_COPYRIGHT_MUSIC (1)
#define FAXE_HX_FmodPortType_VOICE (2)
#define FAXE_HX_FmodPortType_CONTROLLER (3)
#define FAXE_HX_FmodPortType_PERSONAL (4)
#define FAXE_HX_FmodPortType_VIBRATION (5)
#define FAXE_HX_FmodPortType_AUX (6)
#define FAXE_HX_FmodPortType_PASSTHROUGH (7)
#define FAXE_HX_FmodPortType_VR_VIBRATION (8)
#define FAXE_HX_FmodPortType_MAX (9)
#define FAXE_HX_FmodPortType_COUNT 10

/* FmodOutputMethod mirrors FMOD_OUTPUT_METHOD */
#define FAXE_HX_FmodOutputMethod_MIX_DIRECT (0)
#define FAXE_HX_FmodOutputMethod_MIX_BUFFERED (1)
#define FAXE_HX_FmodOutputMethod_COUNT 2

/* FmodSystemCallbackType mirrors FMOD_SYSTEM_CALLBACK_TYPE */
#define FAXE_HX_FmodSystemCallbackType_DEVICELISTCHANGED (0x00000001)
#define FAXE_HX_FmodSystemCallbackType_DEVICELOST (0x00000002)
#define FAXE_HX_FmodSystemCallbackType_MEMORYALLOCATIONFAILED (0x00000004)
#define FAXE_HX_FmodSystemCallbackType_THREADCREATED (0x00000008)
#define FAXE_HX_FmodSystemCallbackType_BADDSPCONNECTION (0x00000010)
#define FAXE_HX_FmodSystemCallbackType_PREMIX (0x00000020)
#define FAXE_HX_FmodSystemCallbackType_POSTMIX (0x00000040)
#define FAXE_HX_FmodSystemCallbackType_ERROR (0x00000080)
#define FAXE_HX_FmodSystemCallbackType_THREADDESTROYED (0x00000100)
#define FAXE_HX_FmodSystemCallbackType_PREUPDATE (0x00000200)
#define FAXE_HX_FmodSystemCallbackType_POSTUPDATE (0x00000400)
#define FAXE_HX_FmodSystemCallbackType_RECORDLISTCHANGED (0x00000800)
#define FAXE_HX_FmodSystemCallbackType_BUFFEREDNOMIX (0x00001000)
#define FAXE_HX_FmodSystemCallbackType_DEVICEREINITIALIZE (0x00002000)
#define FAXE_HX_FmodSystemCallbackType_OUTPUTUNDERRUN (0x00004000)
#define FAXE_HX_FmodSystemCallbackType_RECORDPOSITIONCHANGED (0x00008000)
#define FAXE_HX_FmodSystemCallbackType_ALL (0xFFFFFFFF)
#define FAXE_HX_FmodSystemCallbackType_COUNT 17

/* FmodStudioSystemCallbackType mirrors FMOD_STUDIO_SYSTEM_CALLBACK_TYPE */
#define FAXE_HX_FmodStudioSystemCallbackType_PREUPDATE (0x00000001)
#define FAXE_HX_FmodStudioSystemCallbackType_POSTUPDATE (0x00000002)
#define FAXE_HX_FmodStudioSystemCallbackType_BANK_UNLOAD (0x00000004)
#define FAXE_HX_FmodStudioSystemCallbackType_LIVEUPDATE_CONNECTED (0x00000008)
#define FAXE_HX_FmodStudioSystemCallbackType_LIVEUPDATE_DISCONNECTED (0x00000010)
#define FAXE_HX_FmodStudioSystemCallbackType_ALL (0xFFFFFFFF)
#define FAXE_HX_FmodStudioSystemCallbackType_COUNT 6

/* FmodLimits mirrors the FMOD_MAX_ defines */
#define FAXE_HX_FmodLimits_MAX_CHANNEL_WIDTH (32)
#define FAXE_HX_FmodLimits_MAX_SYSTEMS (8)
#define FAXE_HX_FmodLimits_MAX_LISTENERS (8)
#define FAXE_HX_FmodLimits_REVERB_MAXINSTANCES (4)
#define FAXE_HX_FmodLimits_STUDIO_LOAD_MEMORY_ALIGNMENT (32)
#define FAXE_HX_FmodLimits_COUNT 5

/* FmodVersion mirrors the FMOD_VERSION defines */
#define FAXE_HX_FmodVersion_VERSION (0x00020312)
#define FAXE_HX_FmodVersion_COUNT 1

/* DspChannelMixOutput mirrors FMOD_DSP_CHANNELMIX_OUTPUT */
#define FAXE_HX_DspChannelMixOutput_DEFAULT (0)
#define FAXE_HX_DspChannelMixOutput_ALLMONO (1)
#define FAXE_HX_DspChannelMixOutput_ALLSTEREO (2)
#define FAXE_HX_DspChannelMixOutput_ALLQUAD (3)
#define FAXE_HX_DspChannelMixOutput_ALL5POINT1 (4)
#define FAXE_HX_DspChannelMixOutput_ALL7POINT1 (5)
#define FAXE_HX_DspChannelMixOutput_ALLLFE (6)
#define FAXE_HX_DspChannelMixOutput_ALL7POINT1POINT4 (7)
#define FAXE_HX_DspChannelMixOutput_COUNT 8

/* DspEchoDelayChangeMode mirrors FMOD_DSP_ECHO_DELAYCHANGEMODE_TYPE */
#define FAXE_HX_DspEchoDelayChangeMode_FADE (0)
#define FAXE_HX_DspEchoDelayChangeMode_LERP (1)
#define FAXE_HX_DspEchoDelayChangeMode_NONE (2)
#define FAXE_HX_DspEchoDelayChangeMode_COUNT 3

/* DspFftDownmix mirrors FMOD_DSP_FFT_DOWNMIX_TYPE */
#define FAXE_HX_DspFftDownmix_NONE (0)
#define FAXE_HX_DspFftDownmix_MONO (1)
#define FAXE_HX_DspFftDownmix_COUNT 2

/* DspFftWindow mirrors FMOD_DSP_FFT_WINDOW_TYPE */
#define FAXE_HX_DspFftWindow_RECT (0)
#define FAXE_HX_DspFftWindow_TRIANGLE (1)
#define FAXE_HX_DspFftWindow_HAMMING (2)
#define FAXE_HX_DspFftWindow_HANNING (3)
#define FAXE_HX_DspFftWindow_BLACKMAN (4)
#define FAXE_HX_DspFftWindow_BLACKMANHARRIS (5)
#define FAXE_HX_DspFftWindow_COUNT 6

/* DspLoudnessMeterState mirrors FMOD_DSP_LOUDNESS_METER_STATE_TYPE */
#define FAXE_HX_DspLoudnessMeterState_RESET_INTEGRATED (-3)
#define FAXE_HX_DspLoudnessMeterState_RESET_MAXPEAK (-2)
#define FAXE_HX_DspLoudnessMeterState_RESET_ALL (-1)
#define FAXE_HX_DspLoudnessMeterState_PAUSED (0)
#define FAXE_HX_DspLoudnessMeterState_ANALYZING (1)
#define FAXE_HX_DspLoudnessMeterState_COUNT 5

/* DspMultibandDynamicsMode mirrors FMOD_DSP_MULTIBAND_DYNAMICS_MODE_TYPE */
#define FAXE_HX_DspMultibandDynamicsMode_DISABLED (0)
#define FAXE_HX_DspMultibandDynamicsMode_COMPRESS_UP (1)
#define FAXE_HX_DspMultibandDynamicsMode_COMPRESS_DOWN (2)
#define FAXE_HX_DspMultibandDynamicsMode_EXPAND_UP (3)
#define FAXE_HX_DspMultibandDynamicsMode_EXPAND_DOWN (4)
#define FAXE_HX_DspMultibandDynamicsMode_COUNT 5

/* DspMultibandEqFilter mirrors FMOD_DSP_MULTIBAND_EQ_FILTER_TYPE */
#define FAXE_HX_DspMultibandEqFilter_DISABLED (0)
#define FAXE_HX_DspMultibandEqFilter_LOWPASS_12DB (1)
#define FAXE_HX_DspMultibandEqFilter_LOWPASS_24DB (2)
#define FAXE_HX_DspMultibandEqFilter_LOWPASS_48DB (3)
#define FAXE_HX_DspMultibandEqFilter_HIGHPASS_12DB (4)
#define FAXE_HX_DspMultibandEqFilter_HIGHPASS_24DB (5)
#define FAXE_HX_DspMultibandEqFilter_HIGHPASS_48DB (6)
#define FAXE_HX_DspMultibandEqFilter_LOWSHELF (7)
#define FAXE_HX_DspMultibandEqFilter_HIGHSHELF (8)
#define FAXE_HX_DspMultibandEqFilter_PEAKING (9)
#define FAXE_HX_DspMultibandEqFilter_BANDPASS (10)
#define FAXE_HX_DspMultibandEqFilter_NOTCH (11)
#define FAXE_HX_DspMultibandEqFilter_ALLPASS (12)
#define FAXE_HX_DspMultibandEqFilter_LOWPASS_6DB (13)
#define FAXE_HX_DspMultibandEqFilter_HIGHPASS_6DB (14)
#define FAXE_HX_DspMultibandEqFilter_COUNT 15

/* DspPanModeType mirrors FMOD_DSP_PAN_MODE_TYPE */
#define FAXE_HX_DspPanModeType_MONO (0)
#define FAXE_HX_DspPanModeType_STEREO (1)
#define FAXE_HX_DspPanModeType_SURROUND (2)
#define FAXE_HX_DspPanModeType_COUNT 3

/* DspPan2DStereoModeType mirrors FMOD_DSP_PAN_2D_STEREO_MODE_TYPE */
#define FAXE_HX_DspPan2DStereoModeType_DISTRIBUTED (0)
#define FAXE_HX_DspPan2DStereoModeType_DISCRETE (1)
#define FAXE_HX_DspPan2DStereoModeType_COUNT 2

/* DspPan3DRolloffType mirrors FMOD_DSP_PAN_3D_ROLLOFF_TYPE */
#define FAXE_HX_DspPan3DRolloffType_LINEARSQUARED (0)
#define FAXE_HX_DspPan3DRolloffType_LINEAR (1)
#define FAXE_HX_DspPan3DRolloffType_INVERSE (2)
#define FAXE_HX_DspPan3DRolloffType_INVERSETAPERED (3)
#define FAXE_HX_DspPan3DRolloffType_CUSTOM (4)
#define FAXE_HX_DspPan3DRolloffType_COUNT 5

/* DspPan3DExtentModeType mirrors FMOD_DSP_PAN_3D_EXTENT_MODE_TYPE */
#define FAXE_HX_DspPan3DExtentModeType_AUTO (0)
#define FAXE_HX_DspPan3DExtentModeType_USER (1)
#define FAXE_HX_DspPan3DExtentModeType_OFF (2)
#define FAXE_HX_DspPan3DExtentModeType_COUNT 3

/* DspThreeEqCrossoverSlope mirrors FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_TYPE */
#define FAXE_HX_DspThreeEqCrossoverSlope__12DB (0)
#define FAXE_HX_DspThreeEqCrossoverSlope__24DB (1)
#define FAXE_HX_DspThreeEqCrossoverSlope__48DB (2)
#define FAXE_HX_DspThreeEqCrossoverSlope_COUNT 3

/* DspTransceiverSpeakerMode mirrors FMOD_DSP_TRANSCEIVER_SPEAKERMODE */
#define FAXE_HX_DspTransceiverSpeakerMode_AUTO (-1)
#define FAXE_HX_DspTransceiverSpeakerMode_MONO (0)
#define FAXE_HX_DspTransceiverSpeakerMode_STEREO (1)
#define FAXE_HX_DspTransceiverSpeakerMode_SURROUND (2)
#define FAXE_HX_DspTransceiverSpeakerMode_COUNT 4

#endif
