/*
 * Pins the FMOD value enums declared in Haxe (haxefmod/studio/Types.hx
 * and haxefmod/core/DspEnums.hx) to the numbers in a real FMOD SDK's
 * headers. The Haxe values arrive through faxe_haxe_enums.h, written by
 * ci/haxe-enum-values.py, and every one of them is compared here against
 * the FMOD constant it mirrors. Enums FMOD added in 2.03 are only checked
 * against 2.03 headers.
 *
 *   python3 ci/haxe-enum-values.py --check
 *   gcc -std=c99 -Wall -Wextra -Werror -I<sdk>/api/core/inc -I<sdk>/api/studio/inc \
 *       -o t tests/native/test_faxe_enums.c && ./t
 */
#include <stdio.h>
#include <assert.h>
#include "fmod_common.h"
#include "fmod_dsp_effects.h"
#include "fmod_dsp.h"
#include "fmod_output.h"
#include "fmod_studio_common.h"
#include "faxe_haxe_enums.h"

#define PIN(hx, fmod) assert((int)(hx) == (int)(fmod))

int main(void) {
    /* FMOD_SPEAKER */
    assert(FAXE_HX_FmodSpeaker_COUNT == 14);
    PIN(FAXE_HX_FmodSpeaker_NONE, FMOD_SPEAKER_NONE);
    PIN(FAXE_HX_FmodSpeaker_FRONT_LEFT, FMOD_SPEAKER_FRONT_LEFT);
    PIN(FAXE_HX_FmodSpeaker_FRONT_RIGHT, FMOD_SPEAKER_FRONT_RIGHT);
    PIN(FAXE_HX_FmodSpeaker_FRONT_CENTER, FMOD_SPEAKER_FRONT_CENTER);
    PIN(FAXE_HX_FmodSpeaker_LOW_FREQUENCY, FMOD_SPEAKER_LOW_FREQUENCY);
    PIN(FAXE_HX_FmodSpeaker_SURROUND_LEFT, FMOD_SPEAKER_SURROUND_LEFT);
    PIN(FAXE_HX_FmodSpeaker_SURROUND_RIGHT, FMOD_SPEAKER_SURROUND_RIGHT);
    PIN(FAXE_HX_FmodSpeaker_BACK_LEFT, FMOD_SPEAKER_BACK_LEFT);
    PIN(FAXE_HX_FmodSpeaker_BACK_RIGHT, FMOD_SPEAKER_BACK_RIGHT);
    PIN(FAXE_HX_FmodSpeaker_TOP_FRONT_LEFT, FMOD_SPEAKER_TOP_FRONT_LEFT);
    PIN(FAXE_HX_FmodSpeaker_TOP_FRONT_RIGHT, FMOD_SPEAKER_TOP_FRONT_RIGHT);
    PIN(FAXE_HX_FmodSpeaker_TOP_BACK_LEFT, FMOD_SPEAKER_TOP_BACK_LEFT);
    PIN(FAXE_HX_FmodSpeaker_TOP_BACK_RIGHT, FMOD_SPEAKER_TOP_BACK_RIGHT);
    PIN(FAXE_HX_FmodSpeaker_MAX, FMOD_SPEAKER_MAX);

    /* FMOD_SPEAKERMODE */
    assert(FAXE_HX_FmodSpeakerMode_COUNT == 10);
    PIN(FAXE_HX_FmodSpeakerMode_DEFAULT, FMOD_SPEAKERMODE_DEFAULT);
    PIN(FAXE_HX_FmodSpeakerMode_RAW, FMOD_SPEAKERMODE_RAW);
    PIN(FAXE_HX_FmodSpeakerMode_MONO, FMOD_SPEAKERMODE_MONO);
    PIN(FAXE_HX_FmodSpeakerMode_STEREO, FMOD_SPEAKERMODE_STEREO);
    PIN(FAXE_HX_FmodSpeakerMode_QUAD, FMOD_SPEAKERMODE_QUAD);
    PIN(FAXE_HX_FmodSpeakerMode_SURROUND, FMOD_SPEAKERMODE_SURROUND);
    PIN(FAXE_HX_FmodSpeakerMode__5POINT1, FMOD_SPEAKERMODE_5POINT1);
    PIN(FAXE_HX_FmodSpeakerMode__7POINT1, FMOD_SPEAKERMODE_7POINT1);
    PIN(FAXE_HX_FmodSpeakerMode__7POINT1POINT4, FMOD_SPEAKERMODE_7POINT1POINT4);
    PIN(FAXE_HX_FmodSpeakerMode_MAX, FMOD_SPEAKERMODE_MAX);

    /* FMOD_OUTPUTTYPE */
    assert(FAXE_HX_FmodOutputType_COUNT == 23);
    PIN(FAXE_HX_FmodOutputType_AUTODETECT, FMOD_OUTPUTTYPE_AUTODETECT);
    PIN(FAXE_HX_FmodOutputType_UNKNOWN, FMOD_OUTPUTTYPE_UNKNOWN);
    PIN(FAXE_HX_FmodOutputType_NOSOUND, FMOD_OUTPUTTYPE_NOSOUND);
    PIN(FAXE_HX_FmodOutputType_WAVWRITER, FMOD_OUTPUTTYPE_WAVWRITER);
    PIN(FAXE_HX_FmodOutputType_NOSOUND_NRT, FMOD_OUTPUTTYPE_NOSOUND_NRT);
    PIN(FAXE_HX_FmodOutputType_WAVWRITER_NRT, FMOD_OUTPUTTYPE_WAVWRITER_NRT);
    PIN(FAXE_HX_FmodOutputType_WASAPI, FMOD_OUTPUTTYPE_WASAPI);
    PIN(FAXE_HX_FmodOutputType_ASIO, FMOD_OUTPUTTYPE_ASIO);
    PIN(FAXE_HX_FmodOutputType_PULSEAUDIO, FMOD_OUTPUTTYPE_PULSEAUDIO);
    PIN(FAXE_HX_FmodOutputType_ALSA, FMOD_OUTPUTTYPE_ALSA);
    PIN(FAXE_HX_FmodOutputType_COREAUDIO, FMOD_OUTPUTTYPE_COREAUDIO);
    PIN(FAXE_HX_FmodOutputType_AUDIOTRACK, FMOD_OUTPUTTYPE_AUDIOTRACK);
    PIN(FAXE_HX_FmodOutputType_OPENSL, FMOD_OUTPUTTYPE_OPENSL);
    PIN(FAXE_HX_FmodOutputType_AUDIOOUT, FMOD_OUTPUTTYPE_AUDIOOUT);
    PIN(FAXE_HX_FmodOutputType_AUDIO3D, FMOD_OUTPUTTYPE_AUDIO3D);
    PIN(FAXE_HX_FmodOutputType_WEBAUDIO, FMOD_OUTPUTTYPE_WEBAUDIO);
    PIN(FAXE_HX_FmodOutputType_NNAUDIO, FMOD_OUTPUTTYPE_NNAUDIO);
    PIN(FAXE_HX_FmodOutputType_WINSONIC, FMOD_OUTPUTTYPE_WINSONIC);
    PIN(FAXE_HX_FmodOutputType_AAUDIO, FMOD_OUTPUTTYPE_AAUDIO);
    PIN(FAXE_HX_FmodOutputType_AUDIOWORKLET, FMOD_OUTPUTTYPE_AUDIOWORKLET);
    PIN(FAXE_HX_FmodOutputType_PHASE, FMOD_OUTPUTTYPE_PHASE);
    PIN(FAXE_HX_FmodOutputType_OHAUDIO, FMOD_OUTPUTTYPE_OHAUDIO);
    PIN(FAXE_HX_FmodOutputType_MAX, FMOD_OUTPUTTYPE_MAX);

    /* FMOD_DRIVER_STATE */
    assert(FAXE_HX_FmodDriverState_COUNT == 2);
    PIN(FAXE_HX_FmodDriverState_CONNECTED, FMOD_DRIVER_STATE_CONNECTED);
    PIN(FAXE_HX_FmodDriverState_DEFAULT, FMOD_DRIVER_STATE_DEFAULT);

    /* FMOD_CHANNELMASK */
    assert(FAXE_HX_FmodChannelMask_COUNT == 18);
    PIN(FAXE_HX_FmodChannelMask_FRONT_LEFT, FMOD_CHANNELMASK_FRONT_LEFT);
    PIN(FAXE_HX_FmodChannelMask_FRONT_RIGHT, FMOD_CHANNELMASK_FRONT_RIGHT);
    PIN(FAXE_HX_FmodChannelMask_FRONT_CENTER, FMOD_CHANNELMASK_FRONT_CENTER);
    PIN(FAXE_HX_FmodChannelMask_LOW_FREQUENCY, FMOD_CHANNELMASK_LOW_FREQUENCY);
    PIN(FAXE_HX_FmodChannelMask_SURROUND_LEFT, FMOD_CHANNELMASK_SURROUND_LEFT);
    PIN(FAXE_HX_FmodChannelMask_SURROUND_RIGHT, FMOD_CHANNELMASK_SURROUND_RIGHT);
    PIN(FAXE_HX_FmodChannelMask_BACK_LEFT, FMOD_CHANNELMASK_BACK_LEFT);
    PIN(FAXE_HX_FmodChannelMask_BACK_RIGHT, FMOD_CHANNELMASK_BACK_RIGHT);
    PIN(FAXE_HX_FmodChannelMask_BACK_CENTER, FMOD_CHANNELMASK_BACK_CENTER);
    PIN(FAXE_HX_FmodChannelMask_MONO, FMOD_CHANNELMASK_MONO);
    PIN(FAXE_HX_FmodChannelMask_STEREO, FMOD_CHANNELMASK_STEREO);
    PIN(FAXE_HX_FmodChannelMask_LRC, FMOD_CHANNELMASK_LRC);
    PIN(FAXE_HX_FmodChannelMask_QUAD, FMOD_CHANNELMASK_QUAD);
    PIN(FAXE_HX_FmodChannelMask_SURROUND, FMOD_CHANNELMASK_SURROUND);
    PIN(FAXE_HX_FmodChannelMask__5POINT1, FMOD_CHANNELMASK_5POINT1);
    PIN(FAXE_HX_FmodChannelMask__5POINT1_REARS, FMOD_CHANNELMASK_5POINT1_REARS);
    PIN(FAXE_HX_FmodChannelMask__7POINT0, FMOD_CHANNELMASK_7POINT0);
    PIN(FAXE_HX_FmodChannelMask__7POINT1, FMOD_CHANNELMASK_7POINT1);

    /* FMOD_TIMEUNIT */
    assert(FAXE_HX_FmodTimeUnit_COUNT == 8);
    PIN(FAXE_HX_FmodTimeUnit_MS, FMOD_TIMEUNIT_MS);
    PIN(FAXE_HX_FmodTimeUnit_PCM, FMOD_TIMEUNIT_PCM);
    PIN(FAXE_HX_FmodTimeUnit_PCMBYTES, FMOD_TIMEUNIT_PCMBYTES);
    PIN(FAXE_HX_FmodTimeUnit_RAWBYTES, FMOD_TIMEUNIT_RAWBYTES);
    PIN(FAXE_HX_FmodTimeUnit_PCMFRACTION, FMOD_TIMEUNIT_PCMFRACTION);
    PIN(FAXE_HX_FmodTimeUnit_MODORDER, FMOD_TIMEUNIT_MODORDER);
    PIN(FAXE_HX_FmodTimeUnit_MODROW, FMOD_TIMEUNIT_MODROW);
    PIN(FAXE_HX_FmodTimeUnit_MODPATTERN, FMOD_TIMEUNIT_MODPATTERN);

    /* FMOD_DSP_CHANNELMIX_OUTPUT */
    assert(FAXE_HX_DspChannelMixOutput_COUNT == 8);
    PIN(FAXE_HX_DspChannelMixOutput_DEFAULT, FMOD_DSP_CHANNELMIX_OUTPUT_DEFAULT);
    PIN(FAXE_HX_DspChannelMixOutput_ALLMONO, FMOD_DSP_CHANNELMIX_OUTPUT_ALLMONO);
    PIN(FAXE_HX_DspChannelMixOutput_ALLSTEREO, FMOD_DSP_CHANNELMIX_OUTPUT_ALLSTEREO);
    PIN(FAXE_HX_DspChannelMixOutput_ALLQUAD, FMOD_DSP_CHANNELMIX_OUTPUT_ALLQUAD);
    PIN(FAXE_HX_DspChannelMixOutput_ALL5POINT1, FMOD_DSP_CHANNELMIX_OUTPUT_ALL5POINT1);
    PIN(FAXE_HX_DspChannelMixOutput_ALL7POINT1, FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1);
    PIN(FAXE_HX_DspChannelMixOutput_ALLLFE, FMOD_DSP_CHANNELMIX_OUTPUT_ALLLFE);
    PIN(FAXE_HX_DspChannelMixOutput_ALL7POINT1POINT4, FMOD_DSP_CHANNELMIX_OUTPUT_ALL7POINT1POINT4);

    /* FMOD_DSP_FFT_WINDOW_TYPE */
    assert(FAXE_HX_DspFftWindow_COUNT == 6);
    PIN(FAXE_HX_DspFftWindow_RECT, FMOD_DSP_FFT_WINDOW_RECT);
    PIN(FAXE_HX_DspFftWindow_TRIANGLE, FMOD_DSP_FFT_WINDOW_TRIANGLE);
    PIN(FAXE_HX_DspFftWindow_HAMMING, FMOD_DSP_FFT_WINDOW_HAMMING);
    PIN(FAXE_HX_DspFftWindow_HANNING, FMOD_DSP_FFT_WINDOW_HANNING);
    PIN(FAXE_HX_DspFftWindow_BLACKMAN, FMOD_DSP_FFT_WINDOW_BLACKMAN);
    PIN(FAXE_HX_DspFftWindow_BLACKMANHARRIS, FMOD_DSP_FFT_WINDOW_BLACKMANHARRIS);

    /* FMOD_DSP_LOUDNESS_METER_STATE_TYPE */
    assert(FAXE_HX_DspLoudnessMeterState_COUNT == 5);
    PIN(FAXE_HX_DspLoudnessMeterState_RESET_INTEGRATED, FMOD_DSP_LOUDNESS_METER_STATE_RESET_INTEGRATED);
    PIN(FAXE_HX_DspLoudnessMeterState_RESET_MAXPEAK, FMOD_DSP_LOUDNESS_METER_STATE_RESET_MAXPEAK);
    PIN(FAXE_HX_DspLoudnessMeterState_RESET_ALL, FMOD_DSP_LOUDNESS_METER_STATE_RESET_ALL);
    PIN(FAXE_HX_DspLoudnessMeterState_PAUSED, FMOD_DSP_LOUDNESS_METER_STATE_PAUSED);
    PIN(FAXE_HX_DspLoudnessMeterState_ANALYZING, FMOD_DSP_LOUDNESS_METER_STATE_ANALYZING);

    /* FMOD_DSP_MULTIBAND_EQ_FILTER_TYPE (the 6DB slopes arrived in 2.03) */
    assert(FAXE_HX_DspMultibandEqFilter_COUNT == 15);
    PIN(FAXE_HX_DspMultibandEqFilter_DISABLED, FMOD_DSP_MULTIBAND_EQ_FILTER_DISABLED);
    PIN(FAXE_HX_DspMultibandEqFilter_LOWPASS_12DB, FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_12DB);
    PIN(FAXE_HX_DspMultibandEqFilter_LOWPASS_24DB, FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_24DB);
    PIN(FAXE_HX_DspMultibandEqFilter_LOWPASS_48DB, FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_48DB);
    PIN(FAXE_HX_DspMultibandEqFilter_HIGHPASS_12DB, FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_12DB);
    PIN(FAXE_HX_DspMultibandEqFilter_HIGHPASS_24DB, FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_24DB);
    PIN(FAXE_HX_DspMultibandEqFilter_HIGHPASS_48DB, FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_48DB);
    PIN(FAXE_HX_DspMultibandEqFilter_LOWSHELF, FMOD_DSP_MULTIBAND_EQ_FILTER_LOWSHELF);
    PIN(FAXE_HX_DspMultibandEqFilter_HIGHSHELF, FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHSHELF);
    PIN(FAXE_HX_DspMultibandEqFilter_PEAKING, FMOD_DSP_MULTIBAND_EQ_FILTER_PEAKING);
    PIN(FAXE_HX_DspMultibandEqFilter_BANDPASS, FMOD_DSP_MULTIBAND_EQ_FILTER_BANDPASS);
    PIN(FAXE_HX_DspMultibandEqFilter_NOTCH, FMOD_DSP_MULTIBAND_EQ_FILTER_NOTCH);
    PIN(FAXE_HX_DspMultibandEqFilter_ALLPASS, FMOD_DSP_MULTIBAND_EQ_FILTER_ALLPASS);

    /* FMOD_DSP_PAN_MODE_TYPE */
    assert(FAXE_HX_DspPanModeType_COUNT == 3);
    PIN(FAXE_HX_DspPanModeType_MONO, FMOD_DSP_PAN_MODE_MONO);
    PIN(FAXE_HX_DspPanModeType_STEREO, FMOD_DSP_PAN_MODE_STEREO);
    PIN(FAXE_HX_DspPanModeType_SURROUND, FMOD_DSP_PAN_MODE_SURROUND);

    /* FMOD_DSP_PAN_2D_STEREO_MODE_TYPE */
    assert(FAXE_HX_DspPan2DStereoModeType_COUNT == 2);
    PIN(FAXE_HX_DspPan2DStereoModeType_DISTRIBUTED, FMOD_DSP_PAN_2D_STEREO_MODE_DISTRIBUTED);
    PIN(FAXE_HX_DspPan2DStereoModeType_DISCRETE, FMOD_DSP_PAN_2D_STEREO_MODE_DISCRETE);

    /* FMOD_DSP_PAN_3D_ROLLOFF_TYPE */
    assert(FAXE_HX_DspPan3DRolloffType_COUNT == 5);
    PIN(FAXE_HX_DspPan3DRolloffType_LINEARSQUARED, FMOD_DSP_PAN_3D_ROLLOFF_LINEARSQUARED);
    PIN(FAXE_HX_DspPan3DRolloffType_LINEAR, FMOD_DSP_PAN_3D_ROLLOFF_LINEAR);
    PIN(FAXE_HX_DspPan3DRolloffType_INVERSE, FMOD_DSP_PAN_3D_ROLLOFF_INVERSE);
    PIN(FAXE_HX_DspPan3DRolloffType_INVERSETAPERED, FMOD_DSP_PAN_3D_ROLLOFF_INVERSETAPERED);
    PIN(FAXE_HX_DspPan3DRolloffType_CUSTOM, FMOD_DSP_PAN_3D_ROLLOFF_CUSTOM);

    /* FMOD_DSP_PAN_3D_EXTENT_MODE_TYPE */
    assert(FAXE_HX_DspPan3DExtentModeType_COUNT == 3);
    PIN(FAXE_HX_DspPan3DExtentModeType_AUTO, FMOD_DSP_PAN_3D_EXTENT_MODE_AUTO);
    PIN(FAXE_HX_DspPan3DExtentModeType_USER, FMOD_DSP_PAN_3D_EXTENT_MODE_USER);
    PIN(FAXE_HX_DspPan3DExtentModeType_OFF, FMOD_DSP_PAN_3D_EXTENT_MODE_OFF);

    /* FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_TYPE */
    assert(FAXE_HX_DspThreeEqCrossoverSlope_COUNT == 3);
    PIN(FAXE_HX_DspThreeEqCrossoverSlope__12DB, FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_12DB);
    PIN(FAXE_HX_DspThreeEqCrossoverSlope__24DB, FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_24DB);
    PIN(FAXE_HX_DspThreeEqCrossoverSlope__48DB, FMOD_DSP_THREE_EQ_CROSSOVERSLOPE_48DB);

    /* FMOD_DSP_TRANSCEIVER_SPEAKERMODE */
    assert(FAXE_HX_DspTransceiverSpeakerMode_COUNT == 4);
    PIN(FAXE_HX_DspTransceiverSpeakerMode_AUTO, FMOD_DSP_TRANSCEIVER_SPEAKERMODE_AUTO);
    PIN(FAXE_HX_DspTransceiverSpeakerMode_MONO, FMOD_DSP_TRANSCEIVER_SPEAKERMODE_MONO);
    PIN(FAXE_HX_DspTransceiverSpeakerMode_STEREO, FMOD_DSP_TRANSCEIVER_SPEAKERMODE_STEREO);
    PIN(FAXE_HX_DspTransceiverSpeakerMode_SURROUND, FMOD_DSP_TRANSCEIVER_SPEAKERMODE_SURROUND);

    /* FMOD_STUDIO_STOP_MODE */
    assert(FAXE_HX_FmodStopMode_COUNT == 2);
    PIN(FAXE_HX_FmodStopMode_ALLOWFADEOUT, FMOD_STUDIO_STOP_ALLOWFADEOUT);
    PIN(FAXE_HX_FmodStopMode_IMMEDIATE, FMOD_STUDIO_STOP_IMMEDIATE);

    /* FMOD_STUDIO_PLAYBACK_STATE */
    assert(FAXE_HX_FmodPlaybackState_COUNT == 5);
    PIN(FAXE_HX_FmodPlaybackState_PLAYING, FMOD_STUDIO_PLAYBACK_PLAYING);
    PIN(FAXE_HX_FmodPlaybackState_SUSTAINING, FMOD_STUDIO_PLAYBACK_SUSTAINING);
    PIN(FAXE_HX_FmodPlaybackState_STOPPED, FMOD_STUDIO_PLAYBACK_STOPPED);
    PIN(FAXE_HX_FmodPlaybackState_STARTING, FMOD_STUDIO_PLAYBACK_STARTING);
    PIN(FAXE_HX_FmodPlaybackState_STOPPING, FMOD_STUDIO_PLAYBACK_STOPPING);

    /* FMOD_STUDIO_LOADING_STATE */
    assert(FAXE_HX_FmodLoadingState_COUNT == 5);
    PIN(FAXE_HX_FmodLoadingState_UNLOADING, FMOD_STUDIO_LOADING_STATE_UNLOADING);
    PIN(FAXE_HX_FmodLoadingState_UNLOADED, FMOD_STUDIO_LOADING_STATE_UNLOADED);
    PIN(FAXE_HX_FmodLoadingState_LOADING, FMOD_STUDIO_LOADING_STATE_LOADING);
    PIN(FAXE_HX_FmodLoadingState_LOADED, FMOD_STUDIO_LOADING_STATE_LOADED);
    PIN(FAXE_HX_FmodLoadingState_ERROR, FMOD_STUDIO_LOADING_STATE_ERROR);

    /* FMOD_STUDIO_EVENT_PROPERTY */
    assert(FAXE_HX_FmodEventProperty_COUNT == 7);
    PIN(FAXE_HX_FmodEventProperty_CHANNELPRIORITY, FMOD_STUDIO_EVENT_PROPERTY_CHANNELPRIORITY);
    PIN(FAXE_HX_FmodEventProperty_SCHEDULE_DELAY, FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_DELAY);
    PIN(FAXE_HX_FmodEventProperty_SCHEDULE_LOOKAHEAD, FMOD_STUDIO_EVENT_PROPERTY_SCHEDULE_LOOKAHEAD);
    PIN(FAXE_HX_FmodEventProperty_MINIMUM_DISTANCE, FMOD_STUDIO_EVENT_PROPERTY_MINIMUM_DISTANCE);
    PIN(FAXE_HX_FmodEventProperty_MAXIMUM_DISTANCE, FMOD_STUDIO_EVENT_PROPERTY_MAXIMUM_DISTANCE);
    PIN(FAXE_HX_FmodEventProperty_COOLDOWN, FMOD_STUDIO_EVENT_PROPERTY_COOLDOWN);
    PIN(FAXE_HX_FmodEventProperty_MAX, FMOD_STUDIO_EVENT_PROPERTY_MAX);

    /* FMOD_STUDIO_PARAMETER_TYPE */
    assert(FAXE_HX_FmodParameterType_COUNT == 11);
    PIN(FAXE_HX_FmodParameterType_GAME_CONTROLLED, FMOD_STUDIO_PARAMETER_GAME_CONTROLLED);
    PIN(FAXE_HX_FmodParameterType_AUTOMATIC_DISTANCE, FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE);
    PIN(FAXE_HX_FmodParameterType_AUTOMATIC_EVENT_CONE_ANGLE, FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_CONE_ANGLE);
    PIN(FAXE_HX_FmodParameterType_AUTOMATIC_EVENT_ORIENTATION, FMOD_STUDIO_PARAMETER_AUTOMATIC_EVENT_ORIENTATION);
    PIN(FAXE_HX_FmodParameterType_AUTOMATIC_DIRECTION, FMOD_STUDIO_PARAMETER_AUTOMATIC_DIRECTION);
    PIN(FAXE_HX_FmodParameterType_AUTOMATIC_ELEVATION, FMOD_STUDIO_PARAMETER_AUTOMATIC_ELEVATION);
    PIN(FAXE_HX_FmodParameterType_AUTOMATIC_LISTENER_ORIENTATION, FMOD_STUDIO_PARAMETER_AUTOMATIC_LISTENER_ORIENTATION);
    PIN(FAXE_HX_FmodParameterType_AUTOMATIC_SPEED, FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED);
    PIN(FAXE_HX_FmodParameterType_AUTOMATIC_SPEED_ABSOLUTE, FMOD_STUDIO_PARAMETER_AUTOMATIC_SPEED_ABSOLUTE);
    PIN(FAXE_HX_FmodParameterType_AUTOMATIC_DISTANCE_NORMALIZED, FMOD_STUDIO_PARAMETER_AUTOMATIC_DISTANCE_NORMALIZED);
    PIN(FAXE_HX_FmodParameterType_MAX, FMOD_STUDIO_PARAMETER_MAX);

    /* FMOD_STUDIO_PARAMETER_FLAGS */
    assert(FAXE_HX_FmodParameterFlags_COUNT == 5);
    PIN(FAXE_HX_FmodParameterFlags_READONLY, FMOD_STUDIO_PARAMETER_READONLY);
    PIN(FAXE_HX_FmodParameterFlags_AUTOMATIC, FMOD_STUDIO_PARAMETER_AUTOMATIC);
    PIN(FAXE_HX_FmodParameterFlags_GLOBAL, FMOD_STUDIO_PARAMETER_GLOBAL);
    PIN(FAXE_HX_FmodParameterFlags_DISCRETE, FMOD_STUDIO_PARAMETER_DISCRETE);
    PIN(FAXE_HX_FmodParameterFlags_LABELED, FMOD_STUDIO_PARAMETER_LABELED);

    /* FMOD_STUDIO_USER_PROPERTY_TYPE */
    assert(FAXE_HX_FmodUserPropertyType_COUNT == 4);
    PIN(FAXE_HX_FmodUserPropertyType_INTEGER, FMOD_STUDIO_USER_PROPERTY_TYPE_INTEGER);
    PIN(FAXE_HX_FmodUserPropertyType_BOOLEAN, FMOD_STUDIO_USER_PROPERTY_TYPE_BOOLEAN);
    PIN(FAXE_HX_FmodUserPropertyType_FLOAT, FMOD_STUDIO_USER_PROPERTY_TYPE_FLOAT);
    PIN(FAXE_HX_FmodUserPropertyType_STRING, FMOD_STUDIO_USER_PROPERTY_TYPE_STRING);

    /* FMOD_STUDIO_LOAD_BANK_FLAGS */
    assert(FAXE_HX_FmodLoadBankFlags_COUNT == 4);
    PIN(FAXE_HX_FmodLoadBankFlags_NORMAL, FMOD_STUDIO_LOAD_BANK_NORMAL);
    PIN(FAXE_HX_FmodLoadBankFlags_NONBLOCKING, FMOD_STUDIO_LOAD_BANK_NONBLOCKING);
    PIN(FAXE_HX_FmodLoadBankFlags_DECOMPRESS_SAMPLES, FMOD_STUDIO_LOAD_BANK_DECOMPRESS_SAMPLES);
    PIN(FAXE_HX_FmodLoadBankFlags_UNENCRYPTED, FMOD_STUDIO_LOAD_BANK_UNENCRYPTED);

    /* FMOD_PLUGINTYPE */
    assert(FAXE_HX_FmodPluginType_COUNT == 4);
    PIN(FAXE_HX_FmodPluginType_OUTPUT, FMOD_PLUGINTYPE_OUTPUT);
    PIN(FAXE_HX_FmodPluginType_CODEC, FMOD_PLUGINTYPE_CODEC);
    PIN(FAXE_HX_FmodPluginType_DSP, FMOD_PLUGINTYPE_DSP);
    PIN(FAXE_HX_FmodPluginType_MAX, FMOD_PLUGINTYPE_MAX);

    /* FMOD_TAGTYPE */
    assert(FAXE_HX_FmodTagType_COUNT == 12);
    PIN(FAXE_HX_FmodTagType_UNKNOWN, FMOD_TAGTYPE_UNKNOWN);
    PIN(FAXE_HX_FmodTagType_ID3V1, FMOD_TAGTYPE_ID3V1);
    PIN(FAXE_HX_FmodTagType_ID3V2, FMOD_TAGTYPE_ID3V2);
    PIN(FAXE_HX_FmodTagType_VORBISCOMMENT, FMOD_TAGTYPE_VORBISCOMMENT);
    PIN(FAXE_HX_FmodTagType_SHOUTCAST, FMOD_TAGTYPE_SHOUTCAST);
    PIN(FAXE_HX_FmodTagType_ICECAST, FMOD_TAGTYPE_ICECAST);
    PIN(FAXE_HX_FmodTagType_ASF, FMOD_TAGTYPE_ASF);
    PIN(FAXE_HX_FmodTagType_MIDI, FMOD_TAGTYPE_MIDI);
    PIN(FAXE_HX_FmodTagType_PLAYLIST, FMOD_TAGTYPE_PLAYLIST);
    PIN(FAXE_HX_FmodTagType_FMOD, FMOD_TAGTYPE_FMOD);
    PIN(FAXE_HX_FmodTagType_USER, FMOD_TAGTYPE_USER);
    PIN(FAXE_HX_FmodTagType_MAX, FMOD_TAGTYPE_MAX);

    /* FMOD_TAGDATATYPE */
    assert(FAXE_HX_FmodTagDataType_COUNT == 8);
    PIN(FAXE_HX_FmodTagDataType_BINARY, FMOD_TAGDATATYPE_BINARY);
    PIN(FAXE_HX_FmodTagDataType_INT, FMOD_TAGDATATYPE_INT);
    PIN(FAXE_HX_FmodTagDataType_FLOAT, FMOD_TAGDATATYPE_FLOAT);
    PIN(FAXE_HX_FmodTagDataType_STRING, FMOD_TAGDATATYPE_STRING);
    PIN(FAXE_HX_FmodTagDataType_STRING_UTF16, FMOD_TAGDATATYPE_STRING_UTF16);
    PIN(FAXE_HX_FmodTagDataType_STRING_UTF16BE, FMOD_TAGDATATYPE_STRING_UTF16BE);
    PIN(FAXE_HX_FmodTagDataType_STRING_UTF8, FMOD_TAGDATATYPE_STRING_UTF8);
    PIN(FAXE_HX_FmodTagDataType_MAX, FMOD_TAGDATATYPE_MAX);

    /* FMOD_OPENSTATE */
    assert(FAXE_HX_FmodOpenState_COUNT == 9);
    PIN(FAXE_HX_FmodOpenState_READY, FMOD_OPENSTATE_READY);
    PIN(FAXE_HX_FmodOpenState_LOADING, FMOD_OPENSTATE_LOADING);
    PIN(FAXE_HX_FmodOpenState_ERROR, FMOD_OPENSTATE_ERROR);
    PIN(FAXE_HX_FmodOpenState_CONNECTING, FMOD_OPENSTATE_CONNECTING);
    PIN(FAXE_HX_FmodOpenState_BUFFERING, FMOD_OPENSTATE_BUFFERING);
    PIN(FAXE_HX_FmodOpenState_SEEKING, FMOD_OPENSTATE_SEEKING);
    PIN(FAXE_HX_FmodOpenState_PLAYING, FMOD_OPENSTATE_PLAYING);
    PIN(FAXE_HX_FmodOpenState_SETPOSITION, FMOD_OPENSTATE_SETPOSITION);
    PIN(FAXE_HX_FmodOpenState_MAX, FMOD_OPENSTATE_MAX);

    /* FMOD_SOUND_TYPE */
    assert(FAXE_HX_FmodSoundType_COUNT == 26);
    PIN(FAXE_HX_FmodSoundType_UNKNOWN, FMOD_SOUND_TYPE_UNKNOWN);
    PIN(FAXE_HX_FmodSoundType_AIFF, FMOD_SOUND_TYPE_AIFF);
    PIN(FAXE_HX_FmodSoundType_ASF, FMOD_SOUND_TYPE_ASF);
    PIN(FAXE_HX_FmodSoundType_DLS, FMOD_SOUND_TYPE_DLS);
    PIN(FAXE_HX_FmodSoundType_FLAC, FMOD_SOUND_TYPE_FLAC);
    PIN(FAXE_HX_FmodSoundType_FSB, FMOD_SOUND_TYPE_FSB);
    PIN(FAXE_HX_FmodSoundType_IT, FMOD_SOUND_TYPE_IT);
    PIN(FAXE_HX_FmodSoundType_MIDI, FMOD_SOUND_TYPE_MIDI);
    PIN(FAXE_HX_FmodSoundType_MOD, FMOD_SOUND_TYPE_MOD);
    PIN(FAXE_HX_FmodSoundType_MPEG, FMOD_SOUND_TYPE_MPEG);
    PIN(FAXE_HX_FmodSoundType_OGGVORBIS, FMOD_SOUND_TYPE_OGGVORBIS);
    PIN(FAXE_HX_FmodSoundType_PLAYLIST, FMOD_SOUND_TYPE_PLAYLIST);
    PIN(FAXE_HX_FmodSoundType_RAW, FMOD_SOUND_TYPE_RAW);
    PIN(FAXE_HX_FmodSoundType_S3M, FMOD_SOUND_TYPE_S3M);
    PIN(FAXE_HX_FmodSoundType_USER, FMOD_SOUND_TYPE_USER);
    PIN(FAXE_HX_FmodSoundType_WAV, FMOD_SOUND_TYPE_WAV);
    PIN(FAXE_HX_FmodSoundType_XM, FMOD_SOUND_TYPE_XM);
    PIN(FAXE_HX_FmodSoundType_XMA, FMOD_SOUND_TYPE_XMA);
    PIN(FAXE_HX_FmodSoundType_AUDIOQUEUE, FMOD_SOUND_TYPE_AUDIOQUEUE);
    PIN(FAXE_HX_FmodSoundType_AT9, FMOD_SOUND_TYPE_AT9);
    PIN(FAXE_HX_FmodSoundType_VORBIS, FMOD_SOUND_TYPE_VORBIS);
    PIN(FAXE_HX_FmodSoundType_MEDIA_FOUNDATION, FMOD_SOUND_TYPE_MEDIA_FOUNDATION);
    PIN(FAXE_HX_FmodSoundType_MEDIACODEC, FMOD_SOUND_TYPE_MEDIACODEC);
    PIN(FAXE_HX_FmodSoundType_FADPCM, FMOD_SOUND_TYPE_FADPCM);
    PIN(FAXE_HX_FmodSoundType_OPUS, FMOD_SOUND_TYPE_OPUS);
    PIN(FAXE_HX_FmodSoundType_MAX, FMOD_SOUND_TYPE_MAX);

    /* FMOD_SOUND_FORMAT */
    assert(FAXE_HX_FmodSoundFormat_COUNT == 8);
    PIN(FAXE_HX_FmodSoundFormat_NONE, FMOD_SOUND_FORMAT_NONE);
    PIN(FAXE_HX_FmodSoundFormat_PCM8, FMOD_SOUND_FORMAT_PCM8);
    PIN(FAXE_HX_FmodSoundFormat_PCM16, FMOD_SOUND_FORMAT_PCM16);
    PIN(FAXE_HX_FmodSoundFormat_PCM24, FMOD_SOUND_FORMAT_PCM24);
    PIN(FAXE_HX_FmodSoundFormat_PCM32, FMOD_SOUND_FORMAT_PCM32);
    PIN(FAXE_HX_FmodSoundFormat_PCMFLOAT, FMOD_SOUND_FORMAT_PCMFLOAT);
    PIN(FAXE_HX_FmodSoundFormat_BITSTREAM, FMOD_SOUND_FORMAT_BITSTREAM);
    PIN(FAXE_HX_FmodSoundFormat_MAX, FMOD_SOUND_FORMAT_MAX);

    /* FMOD_STUDIO_INSTANCETYPE */
    assert(FAXE_HX_FmodStudioInstanceType_COUNT == 9);
    PIN(FAXE_HX_FmodStudioInstanceType_NONE, FMOD_STUDIO_INSTANCETYPE_NONE);
    PIN(FAXE_HX_FmodStudioInstanceType_SYSTEM, FMOD_STUDIO_INSTANCETYPE_SYSTEM);
    PIN(FAXE_HX_FmodStudioInstanceType_EVENTDESCRIPTION, FMOD_STUDIO_INSTANCETYPE_EVENTDESCRIPTION);
    PIN(FAXE_HX_FmodStudioInstanceType_EVENTINSTANCE, FMOD_STUDIO_INSTANCETYPE_EVENTINSTANCE);
    PIN(FAXE_HX_FmodStudioInstanceType_PARAMETERINSTANCE, FMOD_STUDIO_INSTANCETYPE_PARAMETERINSTANCE);
    PIN(FAXE_HX_FmodStudioInstanceType_BUS, FMOD_STUDIO_INSTANCETYPE_BUS);
    PIN(FAXE_HX_FmodStudioInstanceType_VCA, FMOD_STUDIO_INSTANCETYPE_VCA);
    PIN(FAXE_HX_FmodStudioInstanceType_BANK, FMOD_STUDIO_INSTANCETYPE_BANK);
    PIN(FAXE_HX_FmodStudioInstanceType_COMMANDREPLAY, FMOD_STUDIO_INSTANCETYPE_COMMANDREPLAY);

    /* FMOD_DSPCONNECTION_TYPE */
    assert(FAXE_HX_DspConnectionType_COUNT == 6);
    PIN(FAXE_HX_DspConnectionType_STANDARD, FMOD_DSPCONNECTION_TYPE_STANDARD);
    PIN(FAXE_HX_DspConnectionType_SIDECHAIN, FMOD_DSPCONNECTION_TYPE_SIDECHAIN);
    PIN(FAXE_HX_DspConnectionType_SEND, FMOD_DSPCONNECTION_TYPE_SEND);
    PIN(FAXE_HX_DspConnectionType_SEND_SIDECHAIN, FMOD_DSPCONNECTION_TYPE_SEND_SIDECHAIN);

    /* FMOD_SOUNDGROUP_BEHAVIOR */
    assert(FAXE_HX_SoundGroupBehavior_COUNT == 4);
    PIN(FAXE_HX_SoundGroupBehavior_FAIL, FMOD_SOUNDGROUP_BEHAVIOR_FAIL);
    PIN(FAXE_HX_SoundGroupBehavior_MUTE, FMOD_SOUNDGROUP_BEHAVIOR_MUTE);
    PIN(FAXE_HX_SoundGroupBehavior_STEALLOWEST, FMOD_SOUNDGROUP_BEHAVIOR_STEALLOWEST);
    PIN(FAXE_HX_SoundGroupBehavior_MAX, FMOD_SOUNDGROUP_BEHAVIOR_MAX);

    /* FMOD_CHANNELCONTROL_DSP_INDEX */
    assert(FAXE_HX_ChannelControlDspIndex_COUNT == 3);
    PIN(FAXE_HX_ChannelControlDspIndex_HEAD, FMOD_CHANNELCONTROL_DSP_HEAD);
    PIN(FAXE_HX_ChannelControlDspIndex_FADER, FMOD_CHANNELCONTROL_DSP_FADER);
    PIN(FAXE_HX_ChannelControlDspIndex_TAIL, FMOD_CHANNELCONTROL_DSP_TAIL);

    /* FMOD_CHANNELCONTROL_TYPE */
    assert(FAXE_HX_FmodChannelControlType_COUNT == 3);
    PIN(FAXE_HX_FmodChannelControlType_CHANNEL, FMOD_CHANNELCONTROL_CHANNEL);
    PIN(FAXE_HX_FmodChannelControlType_CHANNELGROUP, FMOD_CHANNELCONTROL_CHANNELGROUP);
    PIN(FAXE_HX_FmodChannelControlType_MAX, FMOD_CHANNELCONTROL_MAX);

    /* FMOD_CHANNELCONTROL_CALLBACK_TYPE */
    assert(FAXE_HX_FmodChannelControlCallbackType_COUNT == 5);
    PIN(FAXE_HX_FmodChannelControlCallbackType_END, FMOD_CHANNELCONTROL_CALLBACK_END);
    PIN(FAXE_HX_FmodChannelControlCallbackType_VIRTUALVOICE, FMOD_CHANNELCONTROL_CALLBACK_VIRTUALVOICE);
    PIN(FAXE_HX_FmodChannelControlCallbackType_SYNCPOINT, FMOD_CHANNELCONTROL_CALLBACK_SYNCPOINT);
    PIN(FAXE_HX_FmodChannelControlCallbackType_OCCLUSION, FMOD_CHANNELCONTROL_CALLBACK_OCCLUSION);
    PIN(FAXE_HX_FmodChannelControlCallbackType_MAX, FMOD_CHANNELCONTROL_CALLBACK_MAX);

    /* FMOD_CHANNELORDER */
    assert(FAXE_HX_FmodChannelOrder_COUNT == 7);
    PIN(FAXE_HX_FmodChannelOrder_DEFAULT, FMOD_CHANNELORDER_DEFAULT);
    PIN(FAXE_HX_FmodChannelOrder_WAVEFORMAT, FMOD_CHANNELORDER_WAVEFORMAT);
    PIN(FAXE_HX_FmodChannelOrder_PROTOOLS, FMOD_CHANNELORDER_PROTOOLS);
    PIN(FAXE_HX_FmodChannelOrder_ALLMONO, FMOD_CHANNELORDER_ALLMONO);
    PIN(FAXE_HX_FmodChannelOrder_ALLSTEREO, FMOD_CHANNELORDER_ALLSTEREO);
    PIN(FAXE_HX_FmodChannelOrder_ALSA, FMOD_CHANNELORDER_ALSA);
    PIN(FAXE_HX_FmodChannelOrder_MAX, FMOD_CHANNELORDER_MAX);

    /* FMOD_DEBUG_FLAGS */
    assert(FAXE_HX_FmodDebugFlags_COUNT == 12);
    PIN(FAXE_HX_FmodDebugFlags_LEVEL_NONE, FMOD_DEBUG_LEVEL_NONE);
    PIN(FAXE_HX_FmodDebugFlags_LEVEL_ERROR, FMOD_DEBUG_LEVEL_ERROR);
    PIN(FAXE_HX_FmodDebugFlags_LEVEL_WARNING, FMOD_DEBUG_LEVEL_WARNING);
    PIN(FAXE_HX_FmodDebugFlags_LEVEL_LOG, FMOD_DEBUG_LEVEL_LOG);
    PIN(FAXE_HX_FmodDebugFlags_TYPE_MEMORY, FMOD_DEBUG_TYPE_MEMORY);
    PIN(FAXE_HX_FmodDebugFlags_TYPE_FILE, FMOD_DEBUG_TYPE_FILE);
    PIN(FAXE_HX_FmodDebugFlags_TYPE_CODEC, FMOD_DEBUG_TYPE_CODEC);
    PIN(FAXE_HX_FmodDebugFlags_TYPE_TRACE, FMOD_DEBUG_TYPE_TRACE);
    PIN(FAXE_HX_FmodDebugFlags_DISPLAY_TIMESTAMPS, FMOD_DEBUG_DISPLAY_TIMESTAMPS);
    PIN(FAXE_HX_FmodDebugFlags_DISPLAY_LINENUMBERS, FMOD_DEBUG_DISPLAY_LINENUMBERS);
    PIN(FAXE_HX_FmodDebugFlags_DISPLAY_THREAD, FMOD_DEBUG_DISPLAY_THREAD);

    /* FMOD_DEBUG_MODE */
    assert(FAXE_HX_FmodDebugMode_COUNT == 3);
    PIN(FAXE_HX_FmodDebugMode_TTY, FMOD_DEBUG_MODE_TTY);
    PIN(FAXE_HX_FmodDebugMode_FILE, FMOD_DEBUG_MODE_FILE);
    PIN(FAXE_HX_FmodDebugMode_CALLBACK, FMOD_DEBUG_MODE_CALLBACK);

    /* FMOD_INITFLAGS */
    assert(FAXE_HX_FmodInitFlags_COUNT == 14);
    PIN(FAXE_HX_FmodInitFlags_NORMAL, FMOD_INIT_NORMAL);
    PIN(FAXE_HX_FmodInitFlags_STREAM_FROM_UPDATE, FMOD_INIT_STREAM_FROM_UPDATE);
    PIN(FAXE_HX_FmodInitFlags_MIX_FROM_UPDATE, FMOD_INIT_MIX_FROM_UPDATE);
    PIN(FAXE_HX_FmodInitFlags__3D_RIGHTHANDED, FMOD_INIT_3D_RIGHTHANDED);
    PIN(FAXE_HX_FmodInitFlags_CLIP_OUTPUT, FMOD_INIT_CLIP_OUTPUT);
    PIN(FAXE_HX_FmodInitFlags_CHANNEL_LOWPASS, FMOD_INIT_CHANNEL_LOWPASS);
    PIN(FAXE_HX_FmodInitFlags_CHANNEL_DISTANCEFILTER, FMOD_INIT_CHANNEL_DISTANCEFILTER);
    PIN(FAXE_HX_FmodInitFlags_PROFILE_ENABLE, FMOD_INIT_PROFILE_ENABLE);
    PIN(FAXE_HX_FmodInitFlags_VOL0_BECOMES_VIRTUAL, FMOD_INIT_VOL0_BECOMES_VIRTUAL);
    PIN(FAXE_HX_FmodInitFlags_GEOMETRY_USECLOSEST, FMOD_INIT_GEOMETRY_USECLOSEST);
    PIN(FAXE_HX_FmodInitFlags_PREFER_DOLBY_DOWNMIX, FMOD_INIT_PREFER_DOLBY_DOWNMIX);
    PIN(FAXE_HX_FmodInitFlags_THREAD_UNSAFE, FMOD_INIT_THREAD_UNSAFE);
    PIN(FAXE_HX_FmodInitFlags_PROFILE_METER_ALL, FMOD_INIT_PROFILE_METER_ALL);
    PIN(FAXE_HX_FmodInitFlags_MEMORY_TRACKING, FMOD_INIT_MEMORY_TRACKING);

    /* FMOD_STUDIO_INITFLAGS */
    assert(FAXE_HX_FmodStudioInitFlags_COUNT == 7);
    PIN(FAXE_HX_FmodStudioInitFlags_NORMAL, FMOD_STUDIO_INIT_NORMAL);
    PIN(FAXE_HX_FmodStudioInitFlags_LIVEUPDATE, FMOD_STUDIO_INIT_LIVEUPDATE);
    PIN(FAXE_HX_FmodStudioInitFlags_ALLOW_MISSING_PLUGINS, FMOD_STUDIO_INIT_ALLOW_MISSING_PLUGINS);
    PIN(FAXE_HX_FmodStudioInitFlags_SYNCHRONOUS_UPDATE, FMOD_STUDIO_INIT_SYNCHRONOUS_UPDATE);
    PIN(FAXE_HX_FmodStudioInitFlags_DEFERRED_CALLBACKS, FMOD_STUDIO_INIT_DEFERRED_CALLBACKS);
    PIN(FAXE_HX_FmodStudioInitFlags_LOAD_FROM_UPDATE, FMOD_STUDIO_INIT_LOAD_FROM_UPDATE);
    PIN(FAXE_HX_FmodStudioInitFlags_MEMORY_TRACKING, FMOD_STUDIO_INIT_MEMORY_TRACKING);

    /* FMOD_STUDIO_LOAD_MEMORY_MODE */
    assert(FAXE_HX_FmodLoadMemoryMode_COUNT == 2);
    PIN(FAXE_HX_FmodLoadMemoryMode_MEMORY, FMOD_STUDIO_LOAD_MEMORY);
    PIN(FAXE_HX_FmodLoadMemoryMode_MEMORY_POINT, FMOD_STUDIO_LOAD_MEMORY_POINT);

    /* FMOD_STUDIO_COMMANDCAPTURE_FLAGS */
    assert(FAXE_HX_FmodCommandCaptureFlags_COUNT == 3);
    PIN(FAXE_HX_FmodCommandCaptureFlags_NORMAL, FMOD_STUDIO_COMMANDCAPTURE_NORMAL);
    PIN(FAXE_HX_FmodCommandCaptureFlags_FILEFLUSH, FMOD_STUDIO_COMMANDCAPTURE_FILEFLUSH);
    PIN(FAXE_HX_FmodCommandCaptureFlags_SKIP_INITIAL_STATE, FMOD_STUDIO_COMMANDCAPTURE_SKIP_INITIAL_STATE);

    /* FMOD_STUDIO_COMMANDREPLAY_FLAGS */
    assert(FAXE_HX_FmodCommandReplayFlags_COUNT == 4);
    PIN(FAXE_HX_FmodCommandReplayFlags_NORMAL, FMOD_STUDIO_COMMANDREPLAY_NORMAL);
    PIN(FAXE_HX_FmodCommandReplayFlags_SKIP_CLEANUP, FMOD_STUDIO_COMMANDREPLAY_SKIP_CLEANUP);
    PIN(FAXE_HX_FmodCommandReplayFlags_FAST_FORWARD, FMOD_STUDIO_COMMANDREPLAY_FAST_FORWARD);
    PIN(FAXE_HX_FmodCommandReplayFlags_SKIP_BANK_LOAD, FMOD_STUDIO_COMMANDREPLAY_SKIP_BANK_LOAD);

    /* FMOD_MEMORY_TYPE */
    assert(FAXE_HX_FmodMemoryType_COUNT == 8);
    PIN(FAXE_HX_FmodMemoryType_NORMAL, FMOD_MEMORY_NORMAL);
    PIN(FAXE_HX_FmodMemoryType_STREAM_FILE, FMOD_MEMORY_STREAM_FILE);
    PIN(FAXE_HX_FmodMemoryType_STREAM_DECODE, FMOD_MEMORY_STREAM_DECODE);
    PIN(FAXE_HX_FmodMemoryType_SAMPLEDATA, FMOD_MEMORY_SAMPLEDATA);
    PIN(FAXE_HX_FmodMemoryType_DSP_BUFFER, FMOD_MEMORY_DSP_BUFFER);
    PIN(FAXE_HX_FmodMemoryType_PLUGIN, FMOD_MEMORY_PLUGIN);
    PIN(FAXE_HX_FmodMemoryType_PERSISTENT, FMOD_MEMORY_PERSISTENT);
    PIN(FAXE_HX_FmodMemoryType_ALL, FMOD_MEMORY_ALL);

    /* FMOD_THREAD_TYPE */
    assert(FAXE_HX_FmodThreadType_COUNT == 14);
    PIN(FAXE_HX_FmodThreadType_MIXER, FMOD_THREAD_TYPE_MIXER);
    PIN(FAXE_HX_FmodThreadType_FEEDER, FMOD_THREAD_TYPE_FEEDER);
    PIN(FAXE_HX_FmodThreadType_STREAM, FMOD_THREAD_TYPE_STREAM);
    PIN(FAXE_HX_FmodThreadType_FILE, FMOD_THREAD_TYPE_FILE);
    PIN(FAXE_HX_FmodThreadType_NONBLOCKING, FMOD_THREAD_TYPE_NONBLOCKING);
    PIN(FAXE_HX_FmodThreadType_RECORD, FMOD_THREAD_TYPE_RECORD);
    PIN(FAXE_HX_FmodThreadType_GEOMETRY, FMOD_THREAD_TYPE_GEOMETRY);
    PIN(FAXE_HX_FmodThreadType_PROFILER, FMOD_THREAD_TYPE_PROFILER);
    PIN(FAXE_HX_FmodThreadType_STUDIO_UPDATE, FMOD_THREAD_TYPE_STUDIO_UPDATE);
    PIN(FAXE_HX_FmodThreadType_STUDIO_LOAD_BANK, FMOD_THREAD_TYPE_STUDIO_LOAD_BANK);
    PIN(FAXE_HX_FmodThreadType_STUDIO_LOAD_SAMPLE, FMOD_THREAD_TYPE_STUDIO_LOAD_SAMPLE);
    PIN(FAXE_HX_FmodThreadType_CONVOLUTION1, FMOD_THREAD_TYPE_CONVOLUTION1);
    PIN(FAXE_HX_FmodThreadType_CONVOLUTION2, FMOD_THREAD_TYPE_CONVOLUTION2);
    PIN(FAXE_HX_FmodThreadType_MAX, FMOD_THREAD_TYPE_MAX);

    /* FMOD_THREAD_PRIORITY */
    assert(FAXE_HX_FmodThreadPriority_COUNT == 22);
    PIN(FAXE_HX_FmodThreadPriority_PLATFORM_MIN, FMOD_THREAD_PRIORITY_PLATFORM_MIN);
    PIN(FAXE_HX_FmodThreadPriority_PLATFORM_MAX, FMOD_THREAD_PRIORITY_PLATFORM_MAX);
    PIN(FAXE_HX_FmodThreadPriority_DEFAULT, FMOD_THREAD_PRIORITY_DEFAULT);
    PIN(FAXE_HX_FmodThreadPriority_LOW, FMOD_THREAD_PRIORITY_LOW);
    PIN(FAXE_HX_FmodThreadPriority_MEDIUM, FMOD_THREAD_PRIORITY_MEDIUM);
    PIN(FAXE_HX_FmodThreadPriority_HIGH, FMOD_THREAD_PRIORITY_HIGH);
    PIN(FAXE_HX_FmodThreadPriority_VERY_HIGH, FMOD_THREAD_PRIORITY_VERY_HIGH);
    PIN(FAXE_HX_FmodThreadPriority_EXTREME, FMOD_THREAD_PRIORITY_EXTREME);
    PIN(FAXE_HX_FmodThreadPriority_CRITICAL, FMOD_THREAD_PRIORITY_CRITICAL);
    PIN(FAXE_HX_FmodThreadPriority_MIXER, FMOD_THREAD_PRIORITY_MIXER);
    PIN(FAXE_HX_FmodThreadPriority_FEEDER, FMOD_THREAD_PRIORITY_FEEDER);
    PIN(FAXE_HX_FmodThreadPriority_STREAM, FMOD_THREAD_PRIORITY_STREAM);
    PIN(FAXE_HX_FmodThreadPriority_FILE, FMOD_THREAD_PRIORITY_FILE);
    PIN(FAXE_HX_FmodThreadPriority_NONBLOCKING, FMOD_THREAD_PRIORITY_NONBLOCKING);
    PIN(FAXE_HX_FmodThreadPriority_RECORD, FMOD_THREAD_PRIORITY_RECORD);
    PIN(FAXE_HX_FmodThreadPriority_GEOMETRY, FMOD_THREAD_PRIORITY_GEOMETRY);
    PIN(FAXE_HX_FmodThreadPriority_PROFILER, FMOD_THREAD_PRIORITY_PROFILER);
    PIN(FAXE_HX_FmodThreadPriority_STUDIO_UPDATE, FMOD_THREAD_PRIORITY_STUDIO_UPDATE);
    PIN(FAXE_HX_FmodThreadPriority_STUDIO_LOAD_BANK, FMOD_THREAD_PRIORITY_STUDIO_LOAD_BANK);
    PIN(FAXE_HX_FmodThreadPriority_STUDIO_LOAD_SAMPLE, FMOD_THREAD_PRIORITY_STUDIO_LOAD_SAMPLE);
    PIN(FAXE_HX_FmodThreadPriority_CONVOLUTION1, FMOD_THREAD_PRIORITY_CONVOLUTION1);
    PIN(FAXE_HX_FmodThreadPriority_CONVOLUTION2, FMOD_THREAD_PRIORITY_CONVOLUTION2);

    /* FMOD_THREAD_STACK_SIZE */
    assert(FAXE_HX_FmodThreadStackSize_COUNT == 14);
    PIN(FAXE_HX_FmodThreadStackSize_DEFAULT, FMOD_THREAD_STACK_SIZE_DEFAULT);
    PIN(FAXE_HX_FmodThreadStackSize_MIXER, FMOD_THREAD_STACK_SIZE_MIXER);
    PIN(FAXE_HX_FmodThreadStackSize_FEEDER, FMOD_THREAD_STACK_SIZE_FEEDER);
    PIN(FAXE_HX_FmodThreadStackSize_STREAM, FMOD_THREAD_STACK_SIZE_STREAM);
    PIN(FAXE_HX_FmodThreadStackSize_FILE, FMOD_THREAD_STACK_SIZE_FILE);
    PIN(FAXE_HX_FmodThreadStackSize_NONBLOCKING, FMOD_THREAD_STACK_SIZE_NONBLOCKING);
    PIN(FAXE_HX_FmodThreadStackSize_RECORD, FMOD_THREAD_STACK_SIZE_RECORD);
    PIN(FAXE_HX_FmodThreadStackSize_GEOMETRY, FMOD_THREAD_STACK_SIZE_GEOMETRY);
    PIN(FAXE_HX_FmodThreadStackSize_PROFILER, FMOD_THREAD_STACK_SIZE_PROFILER);
    PIN(FAXE_HX_FmodThreadStackSize_STUDIO_UPDATE, FMOD_THREAD_STACK_SIZE_STUDIO_UPDATE);
    PIN(FAXE_HX_FmodThreadStackSize_STUDIO_LOAD_BANK, FMOD_THREAD_STACK_SIZE_STUDIO_LOAD_BANK);
    PIN(FAXE_HX_FmodThreadStackSize_STUDIO_LOAD_SAMPLE, FMOD_THREAD_STACK_SIZE_STUDIO_LOAD_SAMPLE);
    PIN(FAXE_HX_FmodThreadStackSize_CONVOLUTION1, FMOD_THREAD_STACK_SIZE_CONVOLUTION1);
    PIN(FAXE_HX_FmodThreadStackSize_CONVOLUTION2, FMOD_THREAD_STACK_SIZE_CONVOLUTION2);

    /* FMOD_THREAD_AFFINITY (the 32-bit core mask half, the group values do not fit an int) */
    assert(FAXE_HX_FmodThreadAffinity_COUNT == 17);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_ALL, FMOD_THREAD_AFFINITY_CORE_ALL);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_0, FMOD_THREAD_AFFINITY_CORE_0);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_1, FMOD_THREAD_AFFINITY_CORE_1);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_2, FMOD_THREAD_AFFINITY_CORE_2);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_3, FMOD_THREAD_AFFINITY_CORE_3);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_4, FMOD_THREAD_AFFINITY_CORE_4);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_5, FMOD_THREAD_AFFINITY_CORE_5);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_6, FMOD_THREAD_AFFINITY_CORE_6);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_7, FMOD_THREAD_AFFINITY_CORE_7);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_8, FMOD_THREAD_AFFINITY_CORE_8);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_9, FMOD_THREAD_AFFINITY_CORE_9);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_10, FMOD_THREAD_AFFINITY_CORE_10);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_11, FMOD_THREAD_AFFINITY_CORE_11);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_12, FMOD_THREAD_AFFINITY_CORE_12);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_13, FMOD_THREAD_AFFINITY_CORE_13);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_14, FMOD_THREAD_AFFINITY_CORE_14);
    PIN(FAXE_HX_FmodThreadAffinity_CORE_15, FMOD_THREAD_AFFINITY_CORE_15);

    /* FMOD_PORT_INDEX: NONE is all ones in 64 bits, -1 once it crosses as an int */
    assert(FAXE_HX_FmodPortIndex_COUNT == 1);
    assert((FMOD_PORT_INDEX)(long long)FAXE_HX_FmodPortIndex_NONE == (FMOD_PORT_INDEX)FMOD_PORT_INDEX_NONE);

    /* FMOD_MAX_* and the studio alignment, FmodLimits */
    assert(FAXE_HX_FmodLimits_COUNT == 5);
    PIN(FAXE_HX_FmodLimits_MAX_CHANNEL_WIDTH, FMOD_MAX_CHANNEL_WIDTH);
    PIN(FAXE_HX_FmodLimits_MAX_SYSTEMS, FMOD_MAX_SYSTEMS);
    PIN(FAXE_HX_FmodLimits_MAX_LISTENERS, FMOD_MAX_LISTENERS);
    PIN(FAXE_HX_FmodLimits_REVERB_MAXINSTANCES, FMOD_REVERB_MAXINSTANCES);
    PIN(FAXE_HX_FmodLimits_STUDIO_LOAD_MEMORY_ALIGNMENT, FMOD_STUDIO_LOAD_MEMORY_ALIGNMENT);

    /* FMOD_VERSION, FmodVersion: the constant names the SDK the library
     * links, so it is pinned against the 2.03 headers and skipped when this
     * test compiles against the 2.02 compat headers */
    assert(FAXE_HX_FmodVersion_COUNT == 1);
#if FMOD_VERSION >= 0x00020300
    PIN(FAXE_HX_FmodVersion_VERSION, FMOD_VERSION);
#else
    printf("test_enums: FmodVersion pin skipped against FMOD %08x\n", FMOD_VERSION);
#endif

    /* FMOD_DSP_RESAMPLER */
    assert(FAXE_HX_FmodDspResampler_COUNT == 6);
    PIN(FAXE_HX_FmodDspResampler_DEFAULT, FMOD_DSP_RESAMPLER_DEFAULT);
    PIN(FAXE_HX_FmodDspResampler_NOINTERP, FMOD_DSP_RESAMPLER_NOINTERP);
    PIN(FAXE_HX_FmodDspResampler_LINEAR, FMOD_DSP_RESAMPLER_LINEAR);
    PIN(FAXE_HX_FmodDspResampler_CUBIC, FMOD_DSP_RESAMPLER_CUBIC);
    PIN(FAXE_HX_FmodDspResampler_SPLINE, FMOD_DSP_RESAMPLER_SPLINE);
    PIN(FAXE_HX_FmodDspResampler_MAX, FMOD_DSP_RESAMPLER_MAX);

    /* FMOD_DSP_PARAMETER_TYPE */
    assert(FAXE_HX_FmodDspParameterType_COUNT == 5);
    PIN(FAXE_HX_FmodDspParameterType_FLOAT, FMOD_DSP_PARAMETER_TYPE_FLOAT);
    PIN(FAXE_HX_FmodDspParameterType_INT, FMOD_DSP_PARAMETER_TYPE_INT);
    PIN(FAXE_HX_FmodDspParameterType_BOOL, FMOD_DSP_PARAMETER_TYPE_BOOL);
    PIN(FAXE_HX_FmodDspParameterType_DATA, FMOD_DSP_PARAMETER_TYPE_DATA);
    PIN(FAXE_HX_FmodDspParameterType_MAX, FMOD_DSP_PARAMETER_TYPE_MAX);

    /* FMOD_DSP_PARAMETER_DATA_TYPE */
    assert(FAXE_HX_FmodDspParameterDataType_COUNT == 9);
    PIN(FAXE_HX_FmodDspParameterDataType_USER, FMOD_DSP_PARAMETER_DATA_TYPE_USER);
    PIN(FAXE_HX_FmodDspParameterDataType_OVERALLGAIN, FMOD_DSP_PARAMETER_DATA_TYPE_OVERALLGAIN);
    PIN(FAXE_HX_FmodDspParameterDataType__3DATTRIBUTES, FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES);
    PIN(FAXE_HX_FmodDspParameterDataType_SIDECHAIN, FMOD_DSP_PARAMETER_DATA_TYPE_SIDECHAIN);
    PIN(FAXE_HX_FmodDspParameterDataType_FFT, FMOD_DSP_PARAMETER_DATA_TYPE_FFT);
    PIN(FAXE_HX_FmodDspParameterDataType__3DATTRIBUTES_MULTI, FMOD_DSP_PARAMETER_DATA_TYPE_3DATTRIBUTES_MULTI);
    PIN(FAXE_HX_FmodDspParameterDataType_ATTENUATION_RANGE, FMOD_DSP_PARAMETER_DATA_TYPE_ATTENUATION_RANGE);

    /* FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE */
    assert(FAXE_HX_FmodDspParameterFloatMappingType_COUNT == 3);
    PIN(FAXE_HX_FmodDspParameterFloatMappingType_LINEAR, FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_LINEAR);
    PIN(FAXE_HX_FmodDspParameterFloatMappingType_AUTO, FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_AUTO);
    PIN(FAXE_HX_FmodDspParameterFloatMappingType_PIECEWISE_LINEAR, FMOD_DSP_PARAMETER_FLOAT_MAPPING_TYPE_PIECEWISE_LINEAR);

    /* FMOD_DSP_PROCESS_OPERATION */
    assert(FAXE_HX_FmodDspProcessOperation_COUNT == 2);
    PIN(FAXE_HX_FmodDspProcessOperation_PERFORM, FMOD_DSP_PROCESS_PERFORM);
    PIN(FAXE_HX_FmodDspProcessOperation_QUERY, FMOD_DSP_PROCESS_QUERY);

    /* FMOD_DSP_CALLBACK_TYPE */
    assert(FAXE_HX_FmodDspCallbackType_COUNT == 2);
    PIN(FAXE_HX_FmodDspCallbackType_DATAPARAMETERRELEASE, FMOD_DSP_CALLBACK_DATAPARAMETERRELEASE);
    PIN(FAXE_HX_FmodDspCallbackType_MAX, FMOD_DSP_CALLBACK_MAX);

    /* FMOD_DSP_PAN_SURROUND_FLAGS */
    assert(FAXE_HX_FmodDspPanSurroundFlags_COUNT == 2);
    PIN(FAXE_HX_FmodDspPanSurroundFlags_DEFAULT, FMOD_DSP_PAN_SURROUND_DEFAULT);
    PIN(FAXE_HX_FmodDspPanSurroundFlags_ROTATION_NOT_BIASED, FMOD_DSP_PAN_SURROUND_ROTATION_NOT_BIASED);

    /* FMOD_ERRORCALLBACK_INSTANCETYPE */
    assert(FAXE_HX_FmodErrorCallbackInstanceType_COUNT == 19);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_NONE, FMOD_ERRORCALLBACK_INSTANCETYPE_NONE);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_SYSTEM, FMOD_ERRORCALLBACK_INSTANCETYPE_SYSTEM);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_CHANNEL, FMOD_ERRORCALLBACK_INSTANCETYPE_CHANNEL);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_CHANNELGROUP, FMOD_ERRORCALLBACK_INSTANCETYPE_CHANNELGROUP);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_CHANNELCONTROL, FMOD_ERRORCALLBACK_INSTANCETYPE_CHANNELCONTROL);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_SOUND, FMOD_ERRORCALLBACK_INSTANCETYPE_SOUND);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_SOUNDGROUP, FMOD_ERRORCALLBACK_INSTANCETYPE_SOUNDGROUP);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_DSP, FMOD_ERRORCALLBACK_INSTANCETYPE_DSP);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_DSPCONNECTION, FMOD_ERRORCALLBACK_INSTANCETYPE_DSPCONNECTION);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_GEOMETRY, FMOD_ERRORCALLBACK_INSTANCETYPE_GEOMETRY);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_REVERB3D, FMOD_ERRORCALLBACK_INSTANCETYPE_REVERB3D);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_SYSTEM, FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_SYSTEM);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_EVENTDESCRIPTION, FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_EVENTDESCRIPTION);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_EVENTINSTANCE, FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_EVENTINSTANCE);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_PARAMETERINSTANCE, FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_PARAMETERINSTANCE);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_BUS, FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_BUS);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_VCA, FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_VCA);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_BANK, FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_BANK);
    PIN(FAXE_HX_FmodErrorCallbackInstanceType_STUDIO_COMMANDREPLAY, FMOD_ERRORCALLBACK_INSTANCETYPE_STUDIO_COMMANDREPLAY);

    /* FMOD_PORT_TYPE */
    assert(FAXE_HX_FmodPortType_COUNT == 10);
    PIN(FAXE_HX_FmodPortType_MUSIC, FMOD_PORT_TYPE_MUSIC);
    PIN(FAXE_HX_FmodPortType_COPYRIGHT_MUSIC, FMOD_PORT_TYPE_COPYRIGHT_MUSIC);
    PIN(FAXE_HX_FmodPortType_VOICE, FMOD_PORT_TYPE_VOICE);
    PIN(FAXE_HX_FmodPortType_CONTROLLER, FMOD_PORT_TYPE_CONTROLLER);
    PIN(FAXE_HX_FmodPortType_PERSONAL, FMOD_PORT_TYPE_PERSONAL);
    PIN(FAXE_HX_FmodPortType_VIBRATION, FMOD_PORT_TYPE_VIBRATION);
    PIN(FAXE_HX_FmodPortType_AUX, FMOD_PORT_TYPE_AUX);

    /* FMOD_OUTPUT_METHOD */
    assert(FAXE_HX_FmodOutputMethod_COUNT == 2);
    PIN(FAXE_HX_FmodOutputMethod_MIX_DIRECT, FMOD_OUTPUT_METHOD_MIX_DIRECT);
    PIN(FAXE_HX_FmodOutputMethod_MIX_BUFFERED, FMOD_OUTPUT_METHOD_MIX_BUFFERED);

    /* FMOD_SYSTEM_CALLBACK_TYPE */
    assert(FAXE_HX_FmodSystemCallbackType_COUNT == 17);
    PIN(FAXE_HX_FmodSystemCallbackType_DEVICELISTCHANGED, FMOD_SYSTEM_CALLBACK_DEVICELISTCHANGED);
    PIN(FAXE_HX_FmodSystemCallbackType_DEVICELOST, FMOD_SYSTEM_CALLBACK_DEVICELOST);
    PIN(FAXE_HX_FmodSystemCallbackType_MEMORYALLOCATIONFAILED, FMOD_SYSTEM_CALLBACK_MEMORYALLOCATIONFAILED);
    PIN(FAXE_HX_FmodSystemCallbackType_THREADCREATED, FMOD_SYSTEM_CALLBACK_THREADCREATED);
    PIN(FAXE_HX_FmodSystemCallbackType_BADDSPCONNECTION, FMOD_SYSTEM_CALLBACK_BADDSPCONNECTION);
    PIN(FAXE_HX_FmodSystemCallbackType_PREMIX, FMOD_SYSTEM_CALLBACK_PREMIX);
    PIN(FAXE_HX_FmodSystemCallbackType_POSTMIX, FMOD_SYSTEM_CALLBACK_POSTMIX);
    PIN(FAXE_HX_FmodSystemCallbackType_ERROR, FMOD_SYSTEM_CALLBACK_ERROR);
    PIN(FAXE_HX_FmodSystemCallbackType_ALL, FMOD_SYSTEM_CALLBACK_ALL);

    /* FMOD_STUDIO_SYSTEM_CALLBACK_TYPE */
    assert(FAXE_HX_FmodStudioSystemCallbackType_COUNT == 6);
    PIN(FAXE_HX_FmodStudioSystemCallbackType_PREUPDATE, FMOD_STUDIO_SYSTEM_CALLBACK_PREUPDATE);
    PIN(FAXE_HX_FmodStudioSystemCallbackType_POSTUPDATE, FMOD_STUDIO_SYSTEM_CALLBACK_POSTUPDATE);
    PIN(FAXE_HX_FmodStudioSystemCallbackType_BANK_UNLOAD, FMOD_STUDIO_SYSTEM_CALLBACK_BANK_UNLOAD);
    PIN(FAXE_HX_FmodStudioSystemCallbackType_LIVEUPDATE_CONNECTED, FMOD_STUDIO_SYSTEM_CALLBACK_LIVEUPDATE_CONNECTED);
    PIN(FAXE_HX_FmodStudioSystemCallbackType_LIVEUPDATE_DISCONNECTED, FMOD_STUDIO_SYSTEM_CALLBACK_LIVEUPDATE_DISCONNECTED);
    PIN(FAXE_HX_FmodStudioSystemCallbackType_ALL, FMOD_STUDIO_SYSTEM_CALLBACK_ALL);

#if FMOD_VERSION >= 0x00020300
    /* FMOD_SYSTEM_CALLBACK_TYPE, 2.03 dropped MIDMIX and renumbered the bits after it */
    PIN(FAXE_HX_FmodSystemCallbackType_THREADDESTROYED, FMOD_SYSTEM_CALLBACK_THREADDESTROYED);
    PIN(FAXE_HX_FmodSystemCallbackType_PREUPDATE, FMOD_SYSTEM_CALLBACK_PREUPDATE);
    PIN(FAXE_HX_FmodSystemCallbackType_POSTUPDATE, FMOD_SYSTEM_CALLBACK_POSTUPDATE);
    PIN(FAXE_HX_FmodSystemCallbackType_RECORDLISTCHANGED, FMOD_SYSTEM_CALLBACK_RECORDLISTCHANGED);
    PIN(FAXE_HX_FmodSystemCallbackType_BUFFEREDNOMIX, FMOD_SYSTEM_CALLBACK_BUFFEREDNOMIX);
    PIN(FAXE_HX_FmodSystemCallbackType_DEVICEREINITIALIZE, FMOD_SYSTEM_CALLBACK_DEVICEREINITIALIZE);
    PIN(FAXE_HX_FmodSystemCallbackType_OUTPUTUNDERRUN, FMOD_SYSTEM_CALLBACK_OUTPUTUNDERRUN);
    PIN(FAXE_HX_FmodSystemCallbackType_RECORDPOSITIONCHANGED, FMOD_SYSTEM_CALLBACK_RECORDPOSITIONCHANGED);

    /* FMOD_DSPCONNECTION_TYPE, values 2.03 added */
    PIN(FAXE_HX_DspConnectionType_MAX, FMOD_DSPCONNECTION_TYPE_MAX);
    PIN(FAXE_HX_DspConnectionType_PREALLOCATED, FMOD_DSPCONNECTION_TYPE_PREALLOCATED);

    /* FMOD_DEBUG_FLAGS, values 2.03 added */
    PIN(FAXE_HX_FmodDebugFlags_TYPE_VIRTUAL, FMOD_DEBUG_TYPE_VIRTUAL);

    /* FMOD_DSP_PARAMETER_DATA_TYPE, values 2.03 added */
    PIN(FAXE_HX_FmodDspParameterDataType_DYNAMIC_RESPONSE, FMOD_DSP_PARAMETER_DATA_TYPE_DYNAMIC_RESPONSE);
    PIN(FAXE_HX_FmodDspParameterDataType_FINITE_LENGTH, FMOD_DSP_PARAMETER_DATA_TYPE_FINITE_LENGTH);

    /* FMOD_PORT_TYPE, values 2.03 added */
    PIN(FAXE_HX_FmodPortType_MAX, FMOD_PORT_TYPE_MAX);
    PIN(FAXE_HX_FmodPortType_PASSTHROUGH, FMOD_PORT_TYPE_PASSTHROUGH);
    PIN(FAXE_HX_FmodPortType_VR_VIBRATION, FMOD_PORT_TYPE_VR_VIBRATION);

    PIN(FAXE_HX_DspMultibandEqFilter_LOWPASS_6DB, FMOD_DSP_MULTIBAND_EQ_FILTER_LOWPASS_6DB);
    PIN(FAXE_HX_DspMultibandEqFilter_HIGHPASS_6DB, FMOD_DSP_MULTIBAND_EQ_FILTER_HIGHPASS_6DB);

    /* FMOD_DSP_ECHO_DELAYCHANGEMODE_TYPE */
    assert(FAXE_HX_DspEchoDelayChangeMode_COUNT == 3);
    PIN(FAXE_HX_DspEchoDelayChangeMode_FADE, FMOD_DSP_ECHO_DELAYCHANGEMODE_FADE);
    PIN(FAXE_HX_DspEchoDelayChangeMode_LERP, FMOD_DSP_ECHO_DELAYCHANGEMODE_LERP);
    PIN(FAXE_HX_DspEchoDelayChangeMode_NONE, FMOD_DSP_ECHO_DELAYCHANGEMODE_NONE);

    /* FMOD_DSP_FFT_DOWNMIX_TYPE */
    assert(FAXE_HX_DspFftDownmix_COUNT == 2);
    PIN(FAXE_HX_DspFftDownmix_NONE, FMOD_DSP_FFT_DOWNMIX_NONE);
    PIN(FAXE_HX_DspFftDownmix_MONO, FMOD_DSP_FFT_DOWNMIX_MONO);

    /* FMOD_DSP_MULTIBAND_DYNAMICS_MODE_TYPE */
    assert(FAXE_HX_DspMultibandDynamicsMode_COUNT == 5);
    PIN(FAXE_HX_DspMultibandDynamicsMode_DISABLED, FMOD_DSP_MULTIBAND_DYNAMICS_MODE_DISABLED);
    PIN(FAXE_HX_DspMultibandDynamicsMode_COMPRESS_UP, FMOD_DSP_MULTIBAND_DYNAMICS_MODE_COMPRESS_UP);
    PIN(FAXE_HX_DspMultibandDynamicsMode_COMPRESS_DOWN, FMOD_DSP_MULTIBAND_DYNAMICS_MODE_COMPRESS_DOWN);
    PIN(FAXE_HX_DspMultibandDynamicsMode_EXPAND_UP, FMOD_DSP_MULTIBAND_DYNAMICS_MODE_EXPAND_UP);
    PIN(FAXE_HX_DspMultibandDynamicsMode_EXPAND_DOWN, FMOD_DSP_MULTIBAND_DYNAMICS_MODE_EXPAND_DOWN);
#endif

    printf("faxe_enums: all assertions passed (FMOD_VERSION=%#010x)\n",
        (unsigned int)FMOD_VERSION);
    return 0;
}
