/* -------------------------------------------
   FMOD Studio Script by Tanz0rz:
   Export event names as Haxe constants
   -------------------------------------------
 */

studio.menu.addMenuItem({ name: "Export Haxe Constants",  execute: function() {createConstantsFile()} });

const constantsFileName = "FmodConstants.hx";
const constantsOutputLocationFileName = "HaxeConstantsOutputLocation.txt";

function createConstantsFile() {

    var outputPath = readOutputPathFromFile();
    if (!outputPath) {
        alert("Did not find output path for constants file. Exiting...");
        return;
    } 
    outputPath = "{0}\\{1}".format(outputPath, constantsFileName);;
    var constantsFile = studio.system.getFile(outputPath);
    if (!constantsFile.open(studio.system.openMode.WriteOnly)) {    
        alert("Failed to open constants file for writing: " + outputPath + "\n\nCheck the file is not read-only.");
        console.error("Failed to open constants file for writing: " + outputPath);
        return;
    }
    console.log("Opened file: " + outputPath);
    
    writeFileBody(constantsFile);
    constantsFile.close();

    alert("Haxe constants file successfully created at:\n\n" + outputPath);
    console.log("Haxe constants file successfully created at: " + outputPath);
}

function readOutputPathFromFile() {
    const haxeSystemInformationFileLocation = studio.project.filePath.substr(0, studio.project.filePath.lastIndexOf("/") + 1) + constantsOutputLocationFileName;
    haxeSystemInformationFile = studio.system.getFile(haxeSystemInformationFileLocation);
    if (!haxeSystemInformationFile.open(studio.system.openMode.ReadOnly)) {    
        alert("Failed to open file: " + haxeSystemInformationFileLocation + "\n\nMake sure you have a file next to your Fmod Studio project file titled \"" 
        + constantsOutputLocationFileName + "\" and put the file path for where you want your constants file to be saved inside it.");
        console.error("Failed to open file: " + haxeSystemInformationFileLocation + "\n\nMake sure you have a file next to your Fmod Studio project file titled \"" 
        + constantsOutputLocationFileName + "\" and put the file path for where you want your constants file to be saved inside it.");
        return;
    }
    const fileData = haxeSystemInformationFile.readText(10000);
    haxeSystemInformationFile.close();
    return fileData;
}

function writeFileBody(constantsFile) {
    // Write header for file
    constantsFile.writeText("/*\r\n    DO NOT EDIT THIS FILE DIRECTLY\r\n"
    + "    This file was generated by a script in FMOD Studio \r\n*/\r\n\r\n");
    constantsFile.writeText("package;\r\n\r\n")

    // Read all events in from FMOD Studio project
    var allEvents = studio.project.model.Event.findInstances();
    if (allEvents.length === 0) {
        return;
    }

    // Sort events alphabetically 
    allEvents.sort(function(a, b) {
        var pathA = a.getPath().toUpperCase();
        var pathB = b.getPath().toUpperCase();

        if (pathA < pathB) {
            return -1;
        }
        if (pathA > pathB) {
            return 1;        
        }
        return 0;
    });

    // Generate constants for music events
    constantsFile.writeText("enum FmodSongs {\r\n");
    allEvents.forEach(function(object) {
        const path = object.getPath().replace(/(^[0-9])/g, "_$1"); // Don't allow identifier to start with a number

        console.log("Path: " + path);

        if (path.split('/')[1] == "Music") {
            constantsFile.writeText("\t" + path.split('/')[2] + ";\r\n");
        }
    });
    constantsFile.writeText("}\r\n");
    
    // Generate constants for sfx events
    constantsFile.writeText("enum FmodSFX {\r\n");
    allEvents.forEach(function(object) {
        const path = object.getPath().replace(/(^[0-9])/g, "_$1"); // Don't allow identifier to start with a number
        if (path.split('/')[1] == "SFX") {
            constantsFile.writeText("\t" + path.split('/')[2] + ";\r\n");
        }
    });
    constantsFile.writeText("}\r\n");
}