/* -------------------------------------------
   FMOD Studio Script by Tanz0rz:
   Export event names as Haxe constants
   -------------------------------------------
 */

studio.menu.addMenuItem({ 
    name: "Export Event Enums and Build",  
    execute: function() {displayDirectoryPickerModal()},
    keySequence: "Ctrl+B",
});

const constantsFileName = "FmodEventEnum.hx";
const cacheFileName = "CachedHaxeEnumOutputLocation";

function displayDirectoryPickerModal() {

    var outputPathDir = readOutputPathFromFile();
    studio.ui.showModalDialog({
        windowTitle: "Select the folder with your Haxe project's Main class",
        windowWidth: 800,
        windowHeight: 0,
        widgetType: studio.ui.widgetType.Layout,
        layout: studio.ui.layoutType.VBoxLayout,
        items: [
            {
                widgetType: studio.ui.widgetType.Layout,
                layout: studio.ui.layoutType.HBoxLayout,
                contentsMargins: { left: 0, top: 0, right: 0, bottom: 0 },
                items: [
                    { widgetType: studio.ui.widgetType.Spacer, sizePolicy: { horizontalPolicy: studio.ui.sizePolicy.MinimumExpanding } },
                    { widgetType: studio.ui.widgetType.PathLineEdit, stretchFactor: 1, widgetId: "m_directoryPicker", text: outputPathDir, pathType: studio.ui.pathType.Directory},
                    { widgetType: studio.ui.widgetType.PushButton, text: "Save", onClicked: function() {
                        createConstantsFile(this);
                        console.log("Building banks...");
                        studio.project.build();
                        this.closeDialog();
                    }},
                ],
            },
        ],
    });
};

function createConstantsFile(directoryPickerWidget) {

    var outputPath = directoryPickerWidget.findWidget("m_directoryPicker").text();

    const fullOutputPath = "{0}/{1}".format(outputPath, constantsFileName);;
    var constantsFile = studio.system.getFile(fullOutputPath);
    if (!constantsFile.open(studio.system.openMode.WriteOnly)) {    
        alert("Failed to open constants file for writing: " + fullOutputPath + "\n\nCheck the file is not read-only.");
        console.error("Failed to open constants file for writing: " + fullOutputPath);
        return;
    }
    console.log("Opened file: " + fullOutputPath);
    
    writeFileBody(constantsFile);
    constantsFile.close();

    saveOutputPathToFile(outputPath);

    alert("Haxe constants file successfully created in:\n\n" + outputPath);
    console.log("Haxe constants file successfully created in: " + outputPath);
}

function readOutputPathFromFile() {
    const haxeSystemInformationFileLocation = studio.project.filePath.substr(0, studio.project.filePath.lastIndexOf("/") + 1) + cacheFileName;
    haxeSystemInformationFile = studio.system.getFile(haxeSystemInformationFileLocation);
    if (!haxeSystemInformationFile.open(studio.system.openMode.ReadOnly)) {
        return "";
    }
    const fileData = haxeSystemInformationFile.readText(10000);
    haxeSystemInformationFile.close();
    return fileData;
}

function saveOutputPathToFile(outputDir) {
    const haxeSystemInformationFileLocation = studio.project.filePath.substr(0, studio.project.filePath.lastIndexOf("/") + 1) + cacheFileName;
    haxeSystemInformationFile = studio.system.getFile(haxeSystemInformationFileLocation);
    if (!haxeSystemInformationFile.open(studio.system.openMode.WriteOnly)) {
        alert("Failed to open file to cache selected directory: " + haxeSystemInformationFile);
        console.error("Failed to open file to cache selected directory: " + haxeSystemInformationFile);
        return;
    }
    haxeSystemInformationFile.writeText(outputDir);
    haxeSystemInformationFile.close();
}

function writeFileBody(constantsFile) {
    constantsFile.writeText("package;\r\n\r\n");

    // Write header for file
    constantsFile.writeText("/*\r\n    DO NOT EDIT THIS FILE DIRECTLY\r\n"
    + "    This file was generated by a script in FMOD Studio \r\n*/\r\n\r\n");
    constantsFile.writeText("// @formatter:off\r\n");

    // Read all events in from FMOD Studio project
    var allEvents = studio.project.model.Event.findInstances();
    if (allEvents.length === 0) {
        return;
    }

    // Sort events alphabetically 
    allEvents.sort(function(a, b) {
        var pathA = a.getPath().toUpperCase();
        var pathB = b.getPath().toUpperCase();

        if (pathA < pathB) {
            return -1;
        }
        if (pathA > pathB) {
            return 1;        
        }
        return 0;
    });

    var allMusic = [];
    var allSfx = [];

    allEvents.forEach(function(object) {
        // If the event starts with a number, prefix an underscore
        // Replace any whitespace in the event path with underscores
        const path = object.getPath().replace(/(^[0-9])/g, "_$1").replace(/ /g,"_");
        console.log("Path: " + path);

        var finalSlashIndex = path.lastIndexOf('/');
        var eventName = path.substring(finalSlashIndex + 1);
        if (path.split('/')[1] == "Music") {
            allMusic.push({'path': path, 'name': eventName});
        } else if (path.split('/')[1] == "SFX") {
            allSfx.push({'path': path, 'name': eventName});
        }
    });

    console.log("Exporting music event enum")
    constantsFile.writeText("enum FmodSong {\r\n");
    allMusic.forEach(function(event) {
        constantsFile.writeText("    " + event.name + ";\r\n");
    });
    constantsFile.writeText("}\r\n\r\n");
    
    console.log("Exporting SFX event enum")

    constantsFile.writeText("enum FmodSFX {\r\n");
    allSfx.forEach(function(event) {
        constantsFile.writeText("    " + event.name + ";\r\n");
    });
    constantsFile.writeText("}\r\n\r\n");

    console.log("Exporting path util class and functions")
    constantsFile.writeText("class FmodEvent {\r\n");
    constantsFile.writeText("    public static inline extern overload function event(song:FmodSong):String {\r\n");
    constantsFile.writeText("        return switch(song) {\r\n");
    allMusic.forEach(function(event) {
        constantsFile.writeText("            case " + event.name + ": \"" + event.path + "\";\r\n");
    });
    constantsFile.writeText("        }\r\n");
    constantsFile.writeText("    }\r\n");

    constantsFile.writeText("    public static inline extern overload function event(sfx:FmodSFX):String {\r\n");
    constantsFile.writeText("        return switch(sfx) {\r\n");
    allSfx.forEach(function(event) {
        constantsFile.writeText("            case " + event.name + ": \"" + event.path + "\";\r\n");
    });
    constantsFile.writeText("        }\r\n");
    constantsFile.writeText("    }\r\n");
    constantsFile.writeText("}\r\n");
}