/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSongs {
	 public static inline var MainLevel:String = "MainLevel";
}

class FmodSFX {
	 public static inline var Coin:String = "Coin";
	 public static inline var Jump:String = "Jump";
}
