/*
    DO NOT EDIT THIS FILE DIRECTLY
    This file was generated by a script in FMOD Studio 
*/

package;

class FmodSong {
    public static inline var MainLevel:String = "event:/Music/MainLevel";
}

class FmodSFX {
    public static inline var Coin:String = "event:/SFX/Coin";
    public static inline var Jump:String = "event:/SFX/Jump";
}
