#!/usr/bin/env python3
"""Writes the FMOD value enums declared in Haxe as C macros, so a C test
can compare every value against the FMOD headers.

Every `enum abstract X(Int)` in haxefmod/studio/Types.hx and
haxefmod/core/DspEnums.hx whose doc comment names an FMOD type becomes
one FAXE_HX_<X>_<NAME> macro per value plus FAXE_HX_<X>_COUNT, written
to tests/native/faxe_haxe_enums.h. A class of inline constants whose doc
comment names an FMOD_ define family (FmodLimits) is written the same way. tests/native/test_faxe_enums.c
includes that header and asserts each macro against the FMOD constant.

Run: python3 ci/haxe-enum-values.py          rewrite the header
     python3 ci/haxe-enum-values.py --check  fail if it is out of date
"""

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES = [
    os.path.join(ROOT, "haxefmod", "studio", "Types.hx"),
    os.path.join(ROOT, "haxefmod", "core", "DspEnums.hx"),
]
HEADER = os.path.join(ROOT, "tests", "native", "faxe_haxe_enums.h")

ENUM = re.compile(r"/\*\*\s*\*?\s*(FMOD_\w+)(?:(?!\*/).)*?\*/\s*\nenum abstract (\w+)\(Int\)[^{]*\{(.*?)\n\}", re.S)
VALUE = re.compile(r"^\s*var (\w+) = (-?(?:0x[0-9A-Fa-f]+|\d+));", re.M)
# A class of inline constants whose doc comment names an FMOD_ define family
# (FmodLimits) is pinned the same way, one macro per constant
LIMITS = re.compile(r"/\*\*\s*\*?\s*(?:The )?(FMOD_\w+)(?:(?!\*/).)*?\*/\s*\nclass (\w+)\s*\{(.*?)\n\}", re.S)
CONSTANT = re.compile(r"^\s*public static inline var (\w+) = (-?(?:0x[0-9A-Fa-f]+|\d+));", re.M)


def build():
    lines = [
        "/* Generated by ci/haxe-enum-values.py from the Haxe enum sources.",
        " * Do not edit, rerun the script. */",
        "#ifndef FAXE_HAXE_ENUMS_H",
        "#define FAXE_HAXE_ENUMS_H",
        "",
    ]
    for path in SOURCES:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        for match in ENUM.finditer(text):
            fmod_name, name, body = match.groups()
            values = VALUE.findall(body)
            lines.append(f"/* {name} mirrors {fmod_name} */")
            for value_name, value in values:
                lines.append(f"#define FAXE_HX_{name}_{value_name} ({value})")
            lines.append(f"#define FAXE_HX_{name}_COUNT {len(values)}")
            lines.append("")
        for match in LIMITS.finditer(text):
            fmod_name, name, body = match.groups()
            values = CONSTANT.findall(body)
            lines.append(f"/* {name} mirrors the {fmod_name} defines */")
            for value_name, value in values:
                lines.append(f"#define FAXE_HX_{name}_{value_name} ({value})")
            lines.append(f"#define FAXE_HX_{name}_COUNT {len(values)}")
            lines.append("")
    lines.append("#endif")
    return "\n".join(lines) + "\n"


def main():
    text = build()
    if "--check" in sys.argv:
        current = open(HEADER, encoding="utf-8").read() if os.path.exists(HEADER) else ""
        if current != text:
            print(f"{os.path.relpath(HEADER, ROOT)} is out of date, run python3 ci/haxe-enum-values.py")
            return 1
        print(f"{os.path.relpath(HEADER, ROOT)} is up to date")
        return 0
    with open(HEADER, "w", encoding="utf-8") as fh:
        fh.write(text)
    print(f"wrote {os.path.relpath(HEADER, ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
