#!/usr/bin/env python3
"""Builds the example translations the fmod.com docs extension shows on
guide pages.

The FMOD guides carry code examples with C, C++, C#, and JS tabs that are
not function entries, so the bindings table cannot cover them. Their Haxe
versions are written by hand in extension/examples/<page>.md, one file
per fmod.com page (the html file name without the extension). Inside,
each example is a section:

    ## 3
    <!-- 10.2 Extracting PCM Data from a Sound -->
    An optional note shown above the code, one paragraph per line.
    ```haxe
    var sound = ...
    ```

The number is the example's position among the page's example units
(every language selector, and every single-language code block that has
no selector) counted from zero in document order, function entries
included. The extension counts the same way to find it.
The HTML comment records the heading the example sits under. A section
with a note and no code marks an example haxefmod cannot express (the
note says what to do instead). A `## *` section is the page default,
shown for every example on the page that has no section of its own.

Every ```haxe fence is compiled by ci/check-readme-snippets.py, so the
translations stay valid as the library changes.

Run: python3 ci/haxe-examples.py          rewrite extension/examples-data.js
     python3 ci/haxe-examples.py --check  fail if it is out of date
"""

import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE_DIR = os.path.join(ROOT, "extension", "examples")
DATA_JS = os.path.join(ROOT, "extension", "examples-data.js")

SECTION = re.compile(r"^## (\S+)\s*$", re.M)
COMMENT = re.compile(r"<!--(.*?)-->", re.S)
FENCE = re.compile(r"```haxe\n(.*?)```", re.S)


def read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def parse_page(text):
    examples = {}
    matches = list(SECTION.finditer(text))
    for i, match in enumerate(matches):
        # Keys stay strings ("*" and digits alike), which is what JSON
        # gives the extension anyway
        index = match.group(1)
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[match.end():end]
        heading = ""
        comment = COMMENT.search(body)
        if comment:
            heading = comment.group(1).strip()
            body = body[:comment.start()] + body[comment.end():]
        fence = FENCE.search(body)
        code = fence.group(1).rstrip("\n") if fence else None
        if fence:
            body = body[:fence.start()] + body[fence.end():]
        notes = [line.strip() for line in body.splitlines() if line.strip()]
        examples[index] = {"heading": heading, "notes": notes, "code": code}
    return examples


def build():
    pages = {}
    if not os.path.isdir(SOURCE_DIR):
        return pages
    for name in sorted(os.listdir(SOURCE_DIR)):
        if not name.endswith(".md"):
            continue
        page = name[:-3]
        pages[page] = parse_page(read(os.path.join(SOURCE_DIR, name)))
    return pages


def render(pages):
    body = json.dumps(pages, indent=1, sort_keys=True)
    return ("// Generated by ci/haxe-examples.py from extension/examples/*.md.\n"
            "// Do not edit by hand.\n"
            f"const HAXEFMOD_EXAMPLES = {body};\n")


def main():
    check = "--check" in sys.argv[1:]
    pages = build()
    content = render(pages)
    total = sum(len(p) for p in pages.values())
    current = read(DATA_JS) if os.path.exists(DATA_JS) else None
    if current != content:
        if check:
            print("haxe-examples: extension/examples-data.js is out of date (run python3 ci/haxe-examples.py)")
            return 1
        with open(DATA_JS, "w", encoding="utf-8") as fh:
            fh.write(content)
        print("wrote extension/examples-data.js")
    print(f"haxe-examples: {total} examples on {len(pages)} pages")
    return 0


if __name__ == "__main__":
    sys.exit(main())
