package haxefmod.tools;

import haxefmod.tools.StringsBankParser;
import sys.FileSystem;
import sys.io.File;

/**
 * `haxelib run haxefmod generate [--strings <path>] [--out <dir>] [--package <pkg>]`
 *
 * Parses a compiled Master.strings.bank and emits one Haxe class per path
 * category found in it:
 *
 *   FmodEvents.hx      event:/...
 *   FmodBuses.hx       bus:/...
 *   FmodVCAs.hx        vca:/...
 *   FmodSnapshots.hx   snapshot:/...
 *   FmodParameters.hx  parameter:/...
 *
 * Each entry becomes two inline constants: the path and its GUID, e.g.
 *
 *   public static inline var MusicMainLevel:String = "event:/Music/MainLevel";
 *   public static inline var MusicMainLevelGuid:String = "{e5187c3f-...}";
 *
 * Identifier mangling: the category prefix is stripped, the remaining path
 * is split into segments on "/", each segment is split on any character
 * that is not a letter or digit, the first letter of every piece is
 * uppercased, and everything is concatenated ("Vehicles/Ride-on Mower" ->
 * "VehiclesRideOnMower"). An empty result (the bus:/ root) becomes "Root",
 * a leading digit gets an underscore prefix, and duplicate identifiers get
 * numeric suffixes ("Coin", "Coin2", ...).
 */
class Generate {
	static var categories = [
		{prefix: "event:/", className: "FmodEvents", label: "events"},
		{prefix: "bus:/", className: "FmodBuses", label: "buses"},
		{prefix: "vca:/", className: "FmodVCAs", label: "VCAs"},
		{prefix: "snapshot:/", className: "FmodSnapshots", label: "snapshots"},
		{prefix: "parameter:/", className: "FmodParameters", label: "parameters"},
	];

	/** Direct entry point: haxe -cp . --run haxefmod.tools.Generate <flags> */
	public static function main() {
		run(Sys.args(), Sys.getCwd());
	}

	/** Entry point used by Run.hx; cwd is the caller's working directory
		as passed by haxelib run. */
	public static function run(args:Array<String>, cwd:String) {
		var stringsPath:Null<String> = null;
		var outDir:Null<String> = null;
		var pkg = "";

		var i = 0;
		while (i < args.length) {
			switch (args[i]) {
				case "--strings":
					if (i + 1 >= args.length) usageError("--strings requires a path");
					stringsPath = args[++i];
				case "--out":
					if (i + 1 >= args.length) usageError("--out requires a directory");
					outDir = args[++i];
				case "--package":
					if (i + 1 >= args.length) usageError("--package requires a package name");
					pkg = args[++i];
				case arg:
					usageError('unknown argument "$arg"');
			}
			i++;
		}

		if (stringsPath == null) stringsPath = "assets/fmod/Desktop/Master.strings.bank";
		stringsPath = absolute(stringsPath, cwd);

		if (outDir == null) {
			var source = haxe.io.Path.join([cwd, "source"]);
			outDir = (FileSystem.exists(source) && FileSystem.isDirectory(source)) ? source : cwd;
		} else {
			outDir = absolute(outDir, cwd);
		}
		// files go into the package's subdirectory so `-cp <out>` resolves them
		if (pkg != "") outDir = haxe.io.Path.join([outDir].concat(pkg.split(".")));

		var entries = try {
			StringsBankParser.parseFile(stringsPath);
		} catch (e:haxe.Exception) {
			Sys.println(e.message);
			Sys.exit(1);
			return;
		}

		Sys.println('Parsed $stringsPath: ${entries.length} entries');

		var written = 0;
		for (cat in categories) {
			var matched = entries.filter(e -> StringTools.startsWith(e.path, cat.prefix));
			if (matched.length == 0) continue;
			matched.sort((a, b) -> a.path < b.path ? -1 : a.path > b.path ? 1 : 0);

			if (!FileSystem.exists(outDir)) FileSystem.createDirectory(outDir);
			var file = haxe.io.Path.join([outDir, cat.className + ".hx"]);
			File.saveContent(file, emitClass(cat.className, cat.prefix, matched, pkg));
			written++;
			Sys.println('  ${cat.className}.hx: ${matched.length} ${cat.label}');
		}

		if (written == 0) {
			Sys.println("No event:/, bus:/, vca:/, snapshot:/ or parameter:/ paths found - nothing to generate.");
		} else {
			Sys.println('Wrote $written file(s) to $outDir');
		}
	}

	static function emitClass(className:String, prefix:String, entries:Array<StringsBankEntry>, pkg:String):String {
		var lines = new Array<String>();
		lines.push("// Generated by haxelib run haxefmod generate - do not edit");
		lines.push("");
		if (pkg != "") {
			lines.push('package $pkg;');
			lines.push("");
		}
		lines.push('class $className {');
		var names = identifiersFor(entries.map(e -> e.path), prefix);
		for (i in 0...entries.length) {
			lines.push('\tpublic static inline var ${names[i]}:String = "${entries[i].path}";');
			lines.push('\tpublic static inline var ${names[i]}Guid:String = "${entries[i].guid}";');
		}
		lines.push("}");
		lines.push("");
		return lines.join("\n");
	}

	/** Mangles one path into a Haxe identifier (see class doc for the rules). */
	public static function mangle(path:String, prefix:String):String {
		var rest = StringTools.startsWith(path, prefix) ? path.substr(prefix.length) : path;
		var out = new StringBuf();
		var startOfPiece = true;
		for (i in 0...rest.length) {
			var c = rest.charCodeAt(i);
			var isAlpha = (c >= 'a'.code && c <= 'z'.code) || (c >= 'A'.code && c <= 'Z'.code);
			var isDigit = c >= '0'.code && c <= '9'.code;
			if (isAlpha || isDigit) {
				var ch = rest.charAt(i);
				out.add(startOfPiece && isAlpha ? ch.toUpperCase() : ch);
				startOfPiece = false;
			} else {
				startOfPiece = true;
			}
		}
		var name = out.toString();
		if (name == "") return "Root";
		var first = name.charCodeAt(0);
		if (first >= '0'.code && first <= '9'.code) name = "_" + name;
		return name;
	}

	/** Assigns unique identifiers for a list of paths; collisions get
		numeric suffixes. Each name also reserves its "<name>Guid" pair. */
	public static function identifiersFor(paths:Array<String>, prefix:String):Array<String> {
		var used = new Map<String, Bool>();
		var out = new Array<String>();
		for (p in paths) {
			var base = mangle(p, prefix);
			var name = base;
			var n = 2;
			while (used.exists(name) || used.exists(name + "Guid")) {
				name = base + n;
				n++;
			}
			used.set(name, true);
			used.set(name + "Guid", true);
			out.push(name);
		}
		return out;
	}

	static function absolute(path:String, cwd:String):String {
		return haxe.io.Path.isAbsolute(path) ? path : haxe.io.Path.join([cwd, path]);
	}

	static function usageError(message:String) {
		Sys.println('generate: $message');
		Sys.println("Usage: haxelib run haxefmod generate [--strings <path>] [--out <dir>] [--package <pkg>]");
		Sys.println("  --strings  Path to Master.strings.bank (default: assets/fmod/Desktop/Master.strings.bank)");
		Sys.println("  --out      Output directory (default: source/ if it exists, else the current directory)");
		Sys.println("  --package  Package for the generated classes (default: top-level)");
		Sys.exit(1);
	}
}
